# Player Attribute Ratings System

### Setup and Inputs

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
from datetime import datetime

In [2]:
# Load the latest Wyscout dataset available

df = pd.read_csv("Wyscout_League_Export 2026-04-14.csv")

In [3]:
# Create list of unique leagues within dataset

list_unique_leagues = list( sorted( df['League'].unique() ) )
list_unique_leagues

['Albania Superiore League 2024-25',
 'Albania Superiore League 2025-26',
 'Argentina Primera Division 2025',
 'Argentina Primera Division 2026',
 'Australia A-League 2024-25',
 'Australia A-League 2025-26',
 'Austria Bundesliga 2024-25',
 'Austria Bundesliga 2025-26',
 'Belgium First Division A 2024-25',
 'Belgium First Division A 2025-26',
 'Belgium First Division B 2024-25',
 'Belgium First Division B 2025-26',
 'Bolivia Primera Division 2025',
 'Bosnia Premijer Liga 2024-25',
 'Bosnia Premijer Liga 2025-26',
 'Brazil Serie A 2025',
 'Brazil Serie A 2026',
 'Brazil Serie B 2025',
 'Brazil Serie B 2026',
 'Bulgaria First League 2024-25',
 'Bulgaria First League 2025-26',
 'Canada Premier League 2025',
 'Chile Primera Division 2025',
 'Chile Primera Division 2026',
 'China Super League 2025',
 'China Super League 2026',
 'Colombia Primera A 2025',
 'Colombia Primera A 2026',
 'Costa Rica Primera Division 2024-25',
 'Costa Rica Primera Division 2025-26',
 'Croatia 1.HNL 2024-25',
 'Croatia 1.HNL 2025-26',
 'Cyprus First Division 2024-25',
 'Cyprus First Division 2025-26',
 'Czech Fortuna Liga 2024-25',
 'Czech Fortuna Liga 2025-26',
 'Denmark 1st Division 2024-25',
 'Denmark 1st Division 2025-26',
 'Denmark Superliga 2024-25',
 'Denmark Superliga 2025-26',
 'Ecuador Serie A 2025',
 'Ecuador Serie A 2026',
 'Egypt Premier League 2024-25',
 'Egypt Premier League 2025-26',
 'England Championship 2024-25',
 'England Championship 2025-26',
 'England League One 2024-25',
 'England League One 2025-26',
 'England League Two 2024-25',
 'England League Two 2025-26',
 'England National League 2024-25',
 'England National League 2025-26',
 'England National League North South 2024-25',
 'England National League North South 2025-26',
 'England Premier League 2024-25',
 'England Premier League 2025-26',
 'Estonia Meistriliiga 2025',
 'Estonia Meistriliiga 2026',
 'Finland Veikkausliiga 2025',
 'France Championnat National 2024-25',
 'France Championnat National 2025-26',
 'France Ligue 1 2024-25',
 'France Ligue 1 2025-26',
 'France Ligue 2 2024-25',
 'France Ligue 2 2025-26',
 'Georgia Erovnuli Liga 2025',
 'Georgia Erovnuli Liga 2026',
 'Germany 2. Bundesliga 2024-25',
 'Germany 2. Bundesliga 2025-26',
 'Germany 3. Liga 2024-25',
 'Germany 3. Liga 2025-26',
 'Germany Bundesliga 2024-25',
 'Germany Bundesliga 2025-26',
 'Greece Super League 2024-25',
 'Greece Super League 2025-26',
 'Hungary NB1 2024-25',
 'Hungary NB1 2025-26',
 'Indonesia Liga 1 2024-25',
 'Indonesia Liga 1 2025-26',
 'Ireland First Division 2025',
 'Ireland First Division 2026',
 'Ireland Premier Division 2025',
 'Ireland Premier Division 2026',
 "Israel Ligat Ha'Al 2024-25",
 "Israel Ligat Ha'Al 2025-26",
 'Italy Campionato Primavera 1 2024-25',
 'Italy Campionato Primavera 1 2025-26',
 'Italy Serie A 2024-25',
 'Italy Serie A 2025-26',
 'Italy Serie B 2024-25',
 'Italy Serie B 2025-26',
 'Japan J1 100 Year Vision League 2026',
 'Japan J1-League 2025',
 'Japan J2-J3 100 Year Vision League 2026',
 'Japan J2-League 2025',
 'Kazakhstan Premier League 2025',
 'Kazakhstan Premier League 2026',
 'Korea K-League 1 2025',
 'Korea K-League 1 2026',
 'Korea K-League 2 2025',
 'Korea K-League 2 2026',
 'Latvia Virsliga 2025',
 'Latvia Virsliga 2026',
 'Malaysia Super League 2024-25',
 'Malaysia Super League 2025-26',
 'Mexico Liga MX 2024-25',
 'Mexico Liga MX 2025-26',
 'Mexico Liga de Expansion 2024-25',
 'Mexico Liga de Expansion 2025-26',
 'Morocco Botola Pro 2024-25',
 'Morocco Botola Pro 2025-26',
 'Netherlands Eerste Divisie 2024-25',
 'Netherlands Eerste Divisie 2025-26',
 'Netherlands Eredivisie 2024-25',
 'Netherlands Eredivisie 2025-26',
 'Northern Ireland Premiership 2024-25',
 'Northern Ireland Premiership 2025-26',
 'Norway Eliteserien 2025',
 'Norway Eliteserien 2026',
 'Norway First Division 2025',
 'Paraguay Primera Division 2025',
 'Paraguay Primera Division 2026',
 'Peru Primera Division 2025',
 'Peru Primera Division 2026',
 'Poland 1 Liga 2024-25',
 'Poland 1 Liga 2025-26',
 'Poland Ekstraklasa 2024-25',
 'Poland Ekstraklasa 2025-26',
 'Portugal Primeira Liga 2024-25',
 'Portugal Primeira Liga 2025-26',
 'Portugal Segunda Liga 2024-25',
 'Portugal Segunda Liga 2025-26',
 'Romania SuperLiga 2024-25',
 'Romania SuperLiga 2025-26',
 'Russia Premier League 2024-25',
 'Russia Premier League 2025-26',
 'Scotland Championship 2024-25',
 'Scotland Championship 2025-26',
 'Scotland League One 2024-25',
 'Scotland League One 2025-26',
 'Scotland League Two 2024-25',
 'Scotland League Two 2025-26',
 'Scotland Premiership 2024-25',
 'Scotland Premiership 2025-26',
 'Serbia Prva Liga 2025-26',
 'Serbia Super Liga 2024-25',
 'Serbia Super Liga 2025-26',
 'Slovakia Super Liga 2024-25',
 'Slovakia Super Liga 2025-26',
 'Slovenia Prva Liga 2024-25',
 'Slovenia Prva Liga 2025-26',
 'South Africa PSL 2024-25',
 'South Africa PSL 2025-26',
 'Spain La Liga 2024-25',
 'Spain La Liga 2025-26',
 'Spain Primera Division RFEF 2024-25',
 'Spain Primera Division RFEF 2025-26',
 'Spain Segunda 2024-25',
 'Spain Segunda 2025-26',
 'Sweden Allsvenskan 2025',
 'Switzerland Challenge League 2024-25',
 'Switzerland Challenge League 2025-26',
 'Switzerland Super League 2024-25',
 'Switzerland Super League 2025-26',
 'Turkey Super Lig 2024-25',
 'Turkey Super Lig 2025-26',
 'USA MLS 2025',
 'USA MLS 2026',
 'USA MLS Next Pro 2025',
 'USA MLS Next Pro 2026',
 'USA USL Championship 2025',
 'USA USL Championship 2026',
 'USA USL League 1 2025',
 'USA USL League 1 2026',
 'Ukraine Premier League 2024-25',
 'Ukraine Premier League 2025-26',
 'Uruguay Primera Division 2025',
 'Uruguay Primera Division 2026',
 'Uzbekistan Super League 2025',
 'Uzbekistan Super League 2026',
 'Venezuela Primera Division 2025',
 'Venezuela Primera Division 2026']

In [4]:
# Filter settings used later in code

filter_positions = ["CF", "SS"]
filter_leagues = [
                  #'England Premier League 2025-26'
                  'England League One 2025-26',
                  'England League Two 2025-26'
                  ]
filter_minutes = 450

# Columns to exclude from the Z-Score Calculation
excluded_columns = ['Player', 'Team', 'Team within selected timeframe', 'Position','Age', 'Market value', 'Contract expires', 'Matches played', 'Minutes played','Birth country', 'Passport country', 'Foot', 'Height', 'Weight', 'On loan','League', 'Main Position']

# Export names
rating_export_name = "CUFC Ratings - ST.csv"

### Calculate Z-Scores and Export Data for Review

In [5]:
# Create filtered df prior to applying the filters
filtered_df = df.copy()

# Apply filters to the filtered df
filtered_df = filtered_df[ filtered_df['League'].isin(filter_leagues) ]             # filter leagues
filtered_df = filtered_df[ filtered_df['Main Position'].isin(filter_positions) ]    # filter position
filtered_df = filtered_df[ filtered_df['Minutes played'] >= filter_minutes ]        # filter minutes played

filtered_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
874,J. Beesley,Burton Albion,Burton Albion,CF,29.0,300000,30/06/2027,41,4024,13,...,NaN,NaN,0.00,0.00,0.0,0.0,3,100.0,England League One 2025-26,CF
892,K. Wootton,Stockport County,Stockport County,CF,29.0,300000,30/06/2027,40,3827,18,...,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0,England League One 2025-26,CF
911,J. Wareham,Exeter City,Exeter City,CF,22.0,100000,30/06/2027,42,3452,18,...,NaN,NaN,0.00,0.00,0.0,0.0,2,100.0,England League One 2025-26,CF
915,D. Ballard,Leyton Orient,Leyton Orient,CF,21.0,300000,30/06/2028,36,3432,22,...,NaN,NaN,0.00,0.00,0.0,0.0,1,100.0,England League One 2025-26,CF
919,A. Fletcher,Blackpool,Blackpool,CF,30.0,500000,30/06/2026,40,3393,15,...,NaN,NaN,0.00,0.00,0.0,0.0,1,100.0,England League One 2025-26,CF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,"CF, RWF, RW",20.0,0,30/06/2028,12,514,1,...,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0,England League Two 2025-26,CF
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,22.0,0,30/06/2027,8,492,2,...,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0,England League Two 2025-26,CF
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,21.0,0,30/06/2026,14,482,2,...,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0,England League Two 2025-26,CF
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,"CF, AMF",33.0,150000,30/06/2026,17,466,1,...,NaN,NaN,0.19,0.19,0.0,0.0,0,0.0,England League Two 2025-26,CF
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,21.0,0,30/06/2026,12,461,0,...,NaN,NaN,0.00,0.00,0.0,0.0,0,0.0,England League Two 2025-26,CF

In [6]:
# Calculate the z-scores for all metric columns

z_score_df = filtered_df.copy() # create a new df that is a copy of the filtered df

columns_to_zscore = [col for col in filtered_df.columns if col not in excluded_columns] # creates a list of all columns that are not in the excluded list, i.e. a list of columns to convert into z-scores

z_score_df[columns_to_zscore] = z_score_df[columns_to_zscore].apply(zscore) # takes the metric columns subset of the filtered_df, calculates the z-score for each data point and replaces the absolute value with the z-score

# the apply function works column-wise by default - i.e. for each column, calculate the z-score for each value in the column
# then it is assign back into the original filtered_df. This only works because the output (z-scores) are the same length as the input (filtered_df)

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
874,J. Beesley,Burton Albion,Burton Albion,CF,29.0,300000,30/06/2027,41,4024,1.692117,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,2.414537,1.766381,England League One 2025-26,CF
892,K. Wootton,Stockport County,Stockport County,CF,29.0,300000,30/06/2027,40,3827,2.782489,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,-0.602290,-0.600890,England League One 2025-26,CF
911,J. Wareham,Exeter City,Exeter City,CF,22.0,100000,30/06/2027,42,3452,2.782489,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,1.408928,1.766381,England League One 2025-26,CF
915,D. Ballard,Leyton Orient,Leyton Orient,CF,21.0,300000,30/06/2028,36,3432,3.654786,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,0.403319,1.766381,England League One 2025-26,CF
919,A. Fletcher,Blackpool,Blackpool,CF,30.0,500000,30/06/2026,40,3393,2.128266,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,0.403319,1.766381,England League One 2025-26,CF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,"CF, RWF, RW",20.0,0,30/06/2028,12,514,-0.924775,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,-0.602290,-0.600890,England League Two 2025-26,CF
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,22.0,0,30/06/2027,8,492,-0.706701,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,-0.602290,-0.600890,England League Two 2025-26,CF
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,21.0,0,30/06/2026,14,482,-0.706701,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,-0.602290,-0.600890,England League Two 2025-26,CF
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,"CF, AMF",33.0,150000,30/06/2026,17,466,-0.924775,...,NaN,NaN,0.982174,3.208370,-0.260077,-0.19938,-0.602290,-0.600890,England League Two 2025-26,CF
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,21.0,0,30/06/2026,12,461,-1.142850,...,NaN,NaN,-0.238842,-0.360615,-0.260077,-0.19938,-0.602290,-0.600890,England League Two 2025-26,CF

In [7]:
# Function to normalize the data to a [0, 1] range
def NormalizeData(data):
    # Subtract the minimum value from each element and divide by the range
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Iterate over the specified columns (columns_to_zscore) to normalize them
for column in columns_to_zscore:
    # Apply the NormalizeData function to scale the column values
    z_score_df[column] = NormalizeData(z_score_df[column])

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
874,J. Beesley,Burton Albion,Burton Albion,CF,29.0,300000,30/06/2027,41,4024,0.590909,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.6,1.0,England League One 2025-26,CF
892,K. Wootton,Stockport County,Stockport County,CF,29.0,300000,30/06/2027,40,3827,0.818182,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,England League One 2025-26,CF
911,J. Wareham,Exeter City,Exeter City,CF,22.0,100000,30/06/2027,42,3452,0.818182,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.4,1.0,England League One 2025-26,CF
915,D. Ballard,Leyton Orient,Leyton Orient,CF,21.0,300000,30/06/2028,36,3432,1.000000,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.2,1.0,England League One 2025-26,CF
919,A. Fletcher,Blackpool,Blackpool,CF,30.0,500000,30/06/2026,40,3393,0.681818,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.2,1.0,England League One 2025-26,CF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,"CF, RWF, RW",20.0,0,30/06/2028,12,514,0.045455,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,England League Two 2025-26,CF
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,22.0,0,30/06/2027,8,492,0.090909,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,England League Two 2025-26,CF
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,21.0,0,30/06/2026,14,482,0.090909,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,England League Two 2025-26,CF
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,"CF, AMF",33.0,150000,30/06/2026,17,466,0.045455,...,NaN,NaN,0.1,0.513514,0.0,0.0,0.0,0.0,England League Two 2025-26,CF
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,21.0,0,30/06/2026,12,461,0.000000,...,NaN,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,England League Two 2025-26,CF

### Attribute Definition and Calculation

In [8]:
# Create new rating columns in a batch
new_columns = {
                # Template line: 'REPLACE Rating': z_score_df['REPLACE'] * 0,

                # Goal Threat
                'NP goals per 90 Rating': z_score_df['Non-penalty goals per 90']       * 0.25,
                'xG per 90 Rating':                z_score_df['xG per 90']             * 0.25,
                'Shots on target % Rating':       z_score_df['Shots on target, %']     * 0.25,
                'Touches in box per 90 Rating':    z_score_df['Touches in box per 90'] * 0.25,
                
                # Creativity
                'Key passes per 90 Rating': z_score_df['Key passes per 90']                * 0.4,
                'xA per 90 Rating': z_score_df['xA per 90']                                * 0.3,
                'Deep completions per 90 Rating': z_score_df['Deep completions per 90']    * 0.3,
                
                # Dribbling
                'Successful dribbles % Rating': z_score_df['Successful dribbles, %']   * 0.4,
                'Dribbles per 90 Rating': z_score_df['Dribbles per 90']                * 0.4,
                'Accelerations per 90 Rating': z_score_df['Accelerations per 90']      * 0.2,
                
                # Aerial
                'Aerial duels won % Rating': z_score_df['Aerial duels won, %']     * 0.5,
                'Aerial duels per 90 Rating': z_score_df['Aerial duels per 90']    * 0.3,
                'Head goals per 90 Rating': z_score_df['Head goals per 90']        * 0.2,
                
                # Defending (Pressing)
                'Defensive duels won % Rating': z_score_df['Defensive duels won, %']                               * 0.4,
                'Successful defensive actions per 90 Rating': z_score_df['Successful defensive actions per 90']    * 0.3,
                'Defensive duels per 90 Rating': z_score_df['Defensive duels per 90']                              * 0.3,
                }

# Create the new attribute columns using the above ratings columns
# Template line: new_columns['REPLACE Att'] = new_columns['REPLACE'] + new_columns['REPLACE'] + new_columns['REPLACE'] + new_columns['REPLACE']
new_columns['Goal Threat Att']      = new_columns['NP goals per 90 Rating'] + new_columns['xG per 90 Rating'] + new_columns['Shots on target % Rating'] + new_columns['Touches in box per 90 Rating']
new_columns['Creativity Att']   = new_columns['Key passes per 90 Rating'] + new_columns['xA per 90 Rating'] + new_columns['Deep completions per 90 Rating']
new_columns['Dribbling Att']     = new_columns['Successful dribbles % Rating'] + new_columns['Dribbles per 90 Rating'] + new_columns['Accelerations per 90 Rating']
new_columns['Aerial Att']    = new_columns['Aerial duels won % Rating'] + new_columns['Aerial duels per 90 Rating'] + new_columns['Head goals per 90 Rating']
new_columns['Defending Att']    = new_columns['Defensive duels won % Rating'] + new_columns['Successful defensive actions per 90 Rating'] + new_columns['Defensive duels per 90 Rating']

# Add all new columns to the DataFrame at once
z_score_df = pd.concat([z_score_df, pd.DataFrame(new_columns)], axis=1)

# Create a fresh copy of the df to avoid issues if re-running cells
z_score_df = z_score_df.copy()
z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Aerial duels per 90 Rating,Head goals per 90 Rating,Defensive duels won % Rating,Successful defensive actions per 90 Rating,Defensive duels per 90 Rating,Goal Threat Att,Creativity Att,Dribbling Att,Aerial Att,Defending Att
874,J. Beesley,Burton Albion,Burton Albion,CF,29.0,300000,30/06/2027,41,4024,0.590909,...,0.170004,0.037838,0.316352,0.158482,0.075809,0.426105,0.271642,0.168898,0.562055,0.550643
892,K. Wootton,Stockport County,Stockport County,CF,29.0,300000,30/06/2027,40,3827,0.818182,...,0.119277,0.129730,0.263849,0.083929,0.061941,0.481642,0.146600,0.211410,0.739053,0.409719
911,J. Wareham,Exeter City,Exeter City,CF,22.0,100000,30/06/2027,42,3452,0.818182,...,0.117034,0.054054,0.153860,0.090179,0.122958,0.506476,0.128471,0.242116,0.450295,0.366997
915,D. Ballard,Leyton Orient,Leyton Orient,CF,21.0,300000,30/06/2028,36,3432,1.000000,...,0.053718,0.097297,0.292147,0.067857,0.072111,0.593585,0.378836,0.401931,0.321939,0.432115
919,A. Fletcher,Blackpool,Blackpool,CF,30.0,500000,30/06/2026,40,3393,0.681818,...,0.077399,0.016216,0.262514,0.088393,0.078120,0.439815,0.394619,0.375508,0.413342,0.429027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,"CF, RWF, RW",20.0,0,30/06/2028,12,514,0.045455,...,0.041255,0.097297,0.311546,0.258929,0.300000,0.308067,0.350236,0.419545,0.430830,0.870475
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,22.0,0,30/06/2027,8,492,0.090909,...,0.098837,0.000000,0.286719,0.061607,0.078582,0.479556,0.429002,0.422504,0.347982,0.426908
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,21.0,0,30/06/2026,14,482,0.090909,...,0.082634,0.000000,0.400000,0.064286,0.046687,0.504509,0.216263,0.494168,0.318709,0.510973
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,"CF, AMF",33.0,150000,30/06/2026,17,466,0.045455,...,0.098338,0.000000,0.108743,0.000000,0.041140,0.236152,0.094643,0.002536,0.305356,0.149883
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,21.0,0,30/06/2026,12,461,0.000000,...,0.245658,0.000000,0.286719,0.079018,0.042065,0.346565,0.305139,0.279820,0.593436,0.407801

In [9]:
# Create new df containing absolute values to append onto final ratings df later
absolute_columns = [# For join
                    'Player',
                    'Team within selected timeframe',
                    
                    # Goal Threat
                    'Non-penalty goals per 90',
                    'xG per 90',
                    'Shots on target, %',
                    'Touches in box per 90',

                    # Creativity
                    'Key passes per 90',
                    'xA per 90',
                    'Deep completions per 90',

                    # Dribbling
                    'Successful dribbles, %',
                    'Dribbles per 90',
                    'Accelerations per 90',

                    # Aerial
                    'Aerial duels won, %',
                    'Aerial duels per 90',
                    'Head goals per 90',

                    # Defending
                    'Defensive duels won, %',
                    'Successful defensive actions per 90',
                    'Defensive duels per 90',

                    # Set Pieces
                    'Free kicks per 90',
                    'Direct free kicks per 90',
                    'Direct free kicks on target, %',
                    'Corners per 90',
                    
                    ]
absolute_values = filtered_df[absolute_columns].copy()

absolute_values

,Player,Team within selected timeframe,Non-penalty goals per 90,xG per 90,"Shots on target, %",Touches in box per 90,Key passes per 90,xA per 90,Deep completions per 90,"Successful dribbles, %",...,"Aerial duels won, %",Aerial duels per 90,Head goals per 90,"Defensive duels won, %",Successful defensive actions per 90,Defensive duels per 90,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90
874,J. Beesley,Burton Albion,0.22,0.37,39.47,3.09,0.27,0.06,0.56,30.56,...,40.64,15.41,0.07,63.33,5.10,2.68,0.00,0.00,0.0,0.0
892,K. Wootton,Stockport County,0.42,0.30,54.41,2.75,0.12,0.03,0.40,50.00,...,54.15,11.34,0.24,57.43,3.43,2.38,0.00,0.00,0.0,0.0
911,J. Wareham,Exeter City,0.42,0.38,44.05,3.23,0.13,0.02,0.34,56.25,...,33.18,11.16,0.10,45.07,3.57,3.70,0.00,0.00,0.0,0.0
915,D. Ballard,Leyton Orient,0.55,0.44,45.00,3.65,0.45,0.07,0.68,52.08,...,22.41,6.08,0.18,60.61,3.07,2.60,0.00,0.00,0.0,0.0
919,A. Fletcher,Blackpool,0.37,0.32,45.00,2.68,0.40,0.10,0.69,65.79,...,37.21,7.98,0.03,57.28,3.53,2.73,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,0.18,0.22,25.00,3.33,0.35,0.05,0.88,38.10,...,34.48,5.08,0.18,62.79,7.35,7.53,0.00,0.00,0.0,0.0
19880,B. Ihionvien,Shrewsbury Town,0.37,0.37,35.00,3.66,0.55,0.07,0.73,50.00,...,30.19,9.70,0.00,60.00,2.93,2.74,0.00,0.00,0.0,0.0
19883,D. Osong,Fleetwood Town,0.37,0.34,33.33,4.48,0.19,0.07,0.37,47.37,...,28.89,8.40,0.00,72.73,2.99,2.05,0.00,0.00,0.0,0.0
19887,L. Moult,Crewe Alexandra,0.19,0.18,33.33,1.74,0.00,0.00,0.58,0.00,...,26.00,9.66,0.00,40.00,1.55,1.93,0.19,0.19,0.0,0.0
19889,O. Devonport,Fleetwood Town,0.00,0.29,22.22,4.49,0.20,0.08,0.78,44.44,...,40.00,21.48,0.00,60.00,3.32,1.95,0.00,0.00,0.0,0.0

In [10]:
# Creating the new DataFrame 'ratings' with the specified columns
ratings_columns = [
                    "Player", "Team", "Team within selected timeframe", "Main Position", "Position", "League",
                    "Age", "Market value", "Contract expires", "On loan", "Minutes played",
                    
                    # New Att columns created earlier:
                    "Goal Threat Att", "Creativity Att", "Dribbling Att", "Aerial Att", "Defending Att"
                    ]

ratings = z_score_df[ratings_columns].copy()

ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Goal Threat Att,Creativity Att,Dribbling Att,Aerial Att,Defending Att
874,J. Beesley,Burton Albion,Burton Albion,CF,CF,England League One 2025-26,29.0,300000,30/06/2027,no,4024,0.426105,0.271642,0.168898,0.562055,0.550643
892,K. Wootton,Stockport County,Stockport County,CF,CF,England League One 2025-26,29.0,300000,30/06/2027,no,3827,0.481642,0.146600,0.211410,0.739053,0.409719
911,J. Wareham,Exeter City,Exeter City,CF,CF,England League One 2025-26,22.0,100000,30/06/2027,no,3452,0.506476,0.128471,0.242116,0.450295,0.366997
915,D. Ballard,Leyton Orient,Leyton Orient,CF,CF,England League One 2025-26,21.0,300000,30/06/2028,no,3432,0.593585,0.378836,0.401931,0.321939,0.432115
919,A. Fletcher,Blackpool,Blackpool,CF,CF,England League One 2025-26,30.0,500000,30/06/2026,no,3393,0.439815,0.394619,0.375508,0.413342,0.429027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,CF,"CF, RWF, RW",England League Two 2025-26,20.0,0,30/06/2028,yes,514,0.308067,0.350236,0.419545,0.430830,0.870475
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,CF,England League Two 2025-26,22.0,0,30/06/2027,no,492,0.479556,0.429002,0.422504,0.347982,0.426908
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,CF,England League Two 2025-26,21.0,0,30/06/2026,yes,482,0.504509,0.216263,0.494168,0.318709,0.510973
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,CF,"CF, AMF",England League Two 2025-26,33.0,150000,30/06/2026,no,466,0.236152,0.094643,0.002536,0.305356,0.149883
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,CF,England League Two 2025-26,21.0,0,30/06/2026,no,461,0.346565,0.305139,0.279820,0.593436,0.407801

In [11]:
# Normalise the data again after we have created attributes

# Ensure a copy of the DataFrame to prevent unintended changes to the original data
norm_ratings = ratings.copy()

# Select columns that end with the word "Att"
columns_to_normalize = [col for col in norm_ratings.columns if col.endswith('Att')]

# Iterate over the selected columns and apply normalization
for column in columns_to_normalize:

    # Apply the NormalizeData function to scale the column
    norm_ratings[column] = NormalizeData(norm_ratings[column])

norm_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Goal Threat Att,Creativity Att,Dribbling Att,Aerial Att,Defending Att
874,J. Beesley,Burton Albion,Burton Albion,CF,CF,England League One 2025-26,29.0,300000,30/06/2027,no,4024,0.553349,0.323851,0.214514,0.731909,0.582200
892,K. Wootton,Stockport County,Stockport County,CF,CF,England League One 2025-26,29.0,300000,30/06/2027,no,3827,0.629535,0.168163,0.268509,0.966189,0.398110
911,J. Wareham,Exeter City,Exeter City,CF,CF,England League One 2025-26,22.0,100000,30/06/2027,no,3452,0.663603,0.145591,0.307507,0.583981,0.342302
915,D. Ballard,Leyton Orient,Leyton Orient,CF,CF,England League One 2025-26,21.0,300000,30/06/2028,no,3432,0.783097,0.457316,0.510486,0.414084,0.427366
919,A. Fletcher,Blackpool,Blackpool,CF,CF,England League One 2025-26,30.0,500000,30/06/2026,no,3393,0.572157,0.476967,0.476926,0.535068,0.423332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,CF,"CF, RWF, RW",England League Two 2025-26,20.0,0,30/06/2028,yes,514,0.391427,0.421707,0.532857,0.558216,1.000000
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,CF,England League Two 2025-26,22.0,0,30/06/2027,no,492,0.626673,0.519777,0.536615,0.448556,0.420565
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,CF,England League Two 2025-26,21.0,0,30/06/2026,yes,482,0.660904,0.254899,0.627634,0.409809,0.530379
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,CF,"CF, AMF",England League Two 2025-26,33.0,150000,30/06/2026,no,466,0.292775,0.103472,0.003220,0.392135,0.058684
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,CF,England League Two 2025-26,21.0,0,30/06/2026,no,461,0.444238,0.365557,0.355395,0.773446,0.395605

### Weighting the Attributes to Create an Overall Rating

In [12]:
# Weight the overall attributes in terms of importance 
weighted_ratings = norm_ratings.copy()

#Weight the overall ratings
weighted_ratings['Goal Threat Att'] =   weighted_ratings['Goal Threat Att'] * 0.35
weighted_ratings['Creativity Att'] =    weighted_ratings['Creativity Att']  * 0.20
weighted_ratings['Dribbling Att'] =     weighted_ratings['Dribbling Att']   * 0.20
weighted_ratings['Aerial Att'] =        weighted_ratings['Aerial Att']      * 0.15
weighted_ratings['Defending Att'] =     weighted_ratings['Defending Att']   * 0.10


weighted_ratings['ST Rating'] = ( weighted_ratings['Goal Threat Att'] 
                                + weighted_ratings['Creativity Att'] 
                                + weighted_ratings['Dribbling Att'] 
                                + weighted_ratings['Aerial Att'] 
                                + weighted_ratings['Defending Att']
                                )

weighted_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Goal Threat Att,Creativity Att,Dribbling Att,Aerial Att,Defending Att,ST Rating
874,J. Beesley,Burton Albion,Burton Albion,CF,CF,England League One 2025-26,29.0,300000,30/06/2027,no,4024,0.193672,0.064770,0.042903,0.109786,0.058220,0.469352
892,K. Wootton,Stockport County,Stockport County,CF,CF,England League One 2025-26,29.0,300000,30/06/2027,no,3827,0.220337,0.033633,0.053702,0.144928,0.039811,0.492411
911,J. Wareham,Exeter City,Exeter City,CF,CF,England League One 2025-26,22.0,100000,30/06/2027,no,3452,0.232261,0.029118,0.061501,0.087597,0.034230,0.444708
915,D. Ballard,Leyton Orient,Leyton Orient,CF,CF,England League One 2025-26,21.0,300000,30/06/2028,no,3432,0.274084,0.091463,0.102097,0.062113,0.042737,0.572494
919,A. Fletcher,Blackpool,Blackpool,CF,CF,England League One 2025-26,30.0,500000,30/06/2026,no,3393,0.200255,0.095393,0.095385,0.080260,0.042333,0.513627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19873,A. Loupalo-Bi,Walsall,Walsall,CF,"CF, RWF, RW",England League Two 2025-26,20.0,0,30/06/2028,yes,514,0.136999,0.084341,0.106571,0.083732,0.100000,0.511645
19880,B. Ihionvien,Shrewsbury Town,Shrewsbury Town,CF,CF,England League Two 2025-26,22.0,0,30/06/2027,no,492,0.219336,0.103955,0.107323,0.067283,0.042056,0.539954
19883,D. Osong,Fleetwood Town,Fleetwood Town,CF,CF,England League Two 2025-26,21.0,0,30/06/2026,yes,482,0.231316,0.050980,0.125527,0.061471,0.053038,0.522332
19887,L. Moult,Crewe Alexandra,Crewe Alexandra,CF,"CF, AMF",England League Two 2025-26,33.0,150000,30/06/2026,no,466,0.102471,0.020694,0.000644,0.058820,0.005868,0.188498
19889,O. Devonport,Fleetwood Town U21,Fleetwood Town,CF,CF,England League Two 2025-26,21.0,0,30/06/2026,no,461,0.155483,0.073111,0.071079,0.116017,0.039560,0.455251

In [13]:
# Final time to normalise, this time for the overall rating 

# Ensure a copy of the DataFrame to prevent unintended changes
final_ratings = weighted_ratings.copy()

# Select the attribute and rating columns in the DataFrame
columns_to_normalize = [col for col in final_ratings.columns if col.endswith('Att') or col.endswith('Rating')]

# Normalise the attribute and rating columns
for column in columns_to_normalize:
    final_ratings[column] = NormalizeData(final_ratings[column]) # function defined earlier

# Multiply columns ending with 'Att' or 'Rating' by 100 and round to 2 decimal places
final_ratings[columns_to_normalize] = (final_ratings[columns_to_normalize] * 100).round(2)

# Sort the DataFrame by the last column in descending order
rating_column = [col for col in final_ratings.columns if col.endswith('Rating')]
final_ratings.sort_values(by=rating_column, ascending=False, inplace=True)

# Merge the absolute values
final_ratings = final_ratings.merge(absolute_values,on=['Player','Team within selected timeframe'], how='left')

# Reset the index of the sorted DataFrame to ensure a clean, sequential index
final_ratings.reset_index(drop=True, inplace=True)

# Export the ratings to CSV
final_ratings.to_csv(rating_export_name, index=False)
print(f"Ratings exported at {datetime.now().strftime('%d-%m-%Y %H:%M')}")

final_ratings

Ratings exported at 18-05-2026 16:36

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,...,"Aerial duels won, %",Aerial duels per 90,Head goals per 90,"Defensive duels won, %",Successful defensive actions per 90,Defensive duels per 90,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90
0,N. Méndez-Laing,Milton Keynes Dons,Milton Keynes Dons,CF,"CF, LWF",England League Two 2025-26,33.0,400000,30/06/2026,no,...,21.74,2.61,0.00,61.90,4.49,3.58,0.00,0.00,0.0,0.11
1,A. Sidibeh,Stockport County,Stockport County,CF,"CF, RWF",England League One 2025-26,27.0,0,30/06/2028,no,...,36.49,9.24,0.37,62.96,4.24,3.37,0.00,0.00,0.0,0.00
2,A. Cook,Grimsby Town,Grimsby Town,CF,CF,England League Two 2025-26,35.0,150000,30/06/2026,yes,...,43.68,13.04,0.15,70.83,3.07,1.80,0.00,0.00,0.0,0.00
3,J. Kenny,Bolton Wanderers,Bolton Wanderers,CF,"CF, AMF, RAMF",England League One 2025-26,22.0,175000,31/05/2029,yes,...,26.47,4.94,0.15,71.43,4.07,2.04,0.00,0.00,0.0,0.00
4,R. Oné,Lincoln City,Lincoln City,CF,"CF, RAMF, LAMF",England League One 2025-26,19.0,0,NaN,yes,...,27.50,7.74,0.19,43.48,5.03,4.45,0.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,C. Stockton,Salford City,Salford City,CF,CF,England League Two 2025-26,32.0,200000,30/06/2026,no,...,26.32,3.51,0.00,50.00,1.78,1.23,0.00,0.00,0.0,0.00
183,I. Cameron,Raith Rovers,Barrow,CF,CF,England League Two 2025-26,25.0,225000,31/05/2026,yes,...,31.19,18.83,0.00,30.77,2.59,2.25,0.00,0.00,0.0,0.00
184,K. Hemmings,Barrow,Barrow,CF,CF,England League Two 2025-26,33.0,100000,30/06/2026,no,...,34.86,14.41,0.00,37.50,2.11,2.11,0.00,0.00,0.0,0.00
185,L. Moult,Crewe Alexandra,Crewe Alexandra,CF,"CF, AMF",England League Two 2025-26,33.0,150000,30/06/2026,no,...,26.00,9.66,0.00,40.00,1.55,1.93,0.19,0.19,0.0,0.00
186,E. Kachunga,Cambridge United,Cambridge United,CF,"CF, AMF",England League Two 2025-26,33.0,150000,30/06/2026,no,...,23.08,10.82,0.00,58.33,2.91,3.33,0.00,0.00,0.0,0.00