# Player Attribute Ratings System

### Setup and Inputs

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
from datetime import datetime

In [2]:
# Load the latest Wyscout dataset available

df = pd.read_csv("Wyscout_League_Export 2026-04-14.csv")

In [3]:
# Create list of unique leagues within dataset

list_unique_leagues = list( sorted( df['League'].unique() ) )
list_unique_leagues

['Albania Superiore League 2024-25',
 'Albania Superiore League 2025-26',
 'Argentina Primera Division 2025',
 'Argentina Primera Division 2026',
 'Australia A-League 2024-25',
 'Australia A-League 2025-26',
 'Austria Bundesliga 2024-25',
 'Austria Bundesliga 2025-26',
 'Belgium First Division A 2024-25',
 'Belgium First Division A 2025-26',
 'Belgium First Division B 2024-25',
 'Belgium First Division B 2025-26',
 'Bolivia Primera Division 2025',
 'Bosnia Premijer Liga 2024-25',
 'Bosnia Premijer Liga 2025-26',
 'Brazil Serie A 2025',
 'Brazil Serie A 2026',
 'Brazil Serie B 2025',
 'Brazil Serie B 2026',
 'Bulgaria First League 2024-25',
 'Bulgaria First League 2025-26',
 'Canada Premier League 2025',
 'Chile Primera Division 2025',
 'Chile Primera Division 2026',
 'China Super League 2025',
 'China Super League 2026',
 'Colombia Primera A 2025',
 'Colombia Primera A 2026',
 'Costa Rica Primera Division 2024-25',
 'Costa Rica Primera Division 2025-26',
 'Croatia 1.HNL 2024-25',
 'Croatia 1.HNL 2025-26',
 'Cyprus First Division 2024-25',
 'Cyprus First Division 2025-26',
 'Czech Fortuna Liga 2024-25',
 'Czech Fortuna Liga 2025-26',
 'Denmark 1st Division 2024-25',
 'Denmark 1st Division 2025-26',
 'Denmark Superliga 2024-25',
 'Denmark Superliga 2025-26',
 'Ecuador Serie A 2025',
 'Ecuador Serie A 2026',
 'Egypt Premier League 2024-25',
 'Egypt Premier League 2025-26',
 'England Championship 2024-25',
 'England Championship 2025-26',
 'England League One 2024-25',
 'England League One 2025-26',
 'England League Two 2024-25',
 'England League Two 2025-26',
 'England National League 2024-25',
 'England National League 2025-26',
 'England National League North South 2024-25',
 'England National League North South 2025-26',
 'England Premier League 2024-25',
 'England Premier League 2025-26',
 'Estonia Meistriliiga 2025',
 'Estonia Meistriliiga 2026',
 'Finland Veikkausliiga 2025',
 'France Championnat National 2024-25',
 'France Championnat National 2025-26',
 'France Ligue 1 2024-25',
 'France Ligue 1 2025-26',
 'France Ligue 2 2024-25',
 'France Ligue 2 2025-26',
 'Georgia Erovnuli Liga 2025',
 'Georgia Erovnuli Liga 2026',
 'Germany 2. Bundesliga 2024-25',
 'Germany 2. Bundesliga 2025-26',
 'Germany 3. Liga 2024-25',
 'Germany 3. Liga 2025-26',
 'Germany Bundesliga 2024-25',
 'Germany Bundesliga 2025-26',
 'Greece Super League 2024-25',
 'Greece Super League 2025-26',
 'Hungary NB1 2024-25',
 'Hungary NB1 2025-26',
 'Indonesia Liga 1 2024-25',
 'Indonesia Liga 1 2025-26',
 'Ireland First Division 2025',
 'Ireland First Division 2026',
 'Ireland Premier Division 2025',
 'Ireland Premier Division 2026',
 "Israel Ligat Ha'Al 2024-25",
 "Israel Ligat Ha'Al 2025-26",
 'Italy Campionato Primavera 1 2024-25',
 'Italy Campionato Primavera 1 2025-26',
 'Italy Serie A 2024-25',
 'Italy Serie A 2025-26',
 'Italy Serie B 2024-25',
 'Italy Serie B 2025-26',
 'Japan J1 100 Year Vision League 2026',
 'Japan J1-League 2025',
 'Japan J2-J3 100 Year Vision League 2026',
 'Japan J2-League 2025',
 'Kazakhstan Premier League 2025',
 'Kazakhstan Premier League 2026',
 'Korea K-League 1 2025',
 'Korea K-League 1 2026',
 'Korea K-League 2 2025',
 'Korea K-League 2 2026',
 'Latvia Virsliga 2025',
 'Latvia Virsliga 2026',
 'Malaysia Super League 2024-25',
 'Malaysia Super League 2025-26',
 'Mexico Liga MX 2024-25',
 'Mexico Liga MX 2025-26',
 'Mexico Liga de Expansion 2024-25',
 'Mexico Liga de Expansion 2025-26',
 'Morocco Botola Pro 2024-25',
 'Morocco Botola Pro 2025-26',
 'Netherlands Eerste Divisie 2024-25',
 'Netherlands Eerste Divisie 2025-26',
 'Netherlands Eredivisie 2024-25',
 'Netherlands Eredivisie 2025-26',
 'Northern Ireland Premiership 2024-25',
 'Northern Ireland Premiership 2025-26',
 'Norway Eliteserien 2025',
 'Norway Eliteserien 2026',
 'Norway First Division 2025',
 'Paraguay Primera Division 2025',
 'Paraguay Primera Division 2026',
 'Peru Primera Division 2025',
 'Peru Primera Division 2026',
 'Poland 1 Liga 2024-25',
 'Poland 1 Liga 2025-26',
 'Poland Ekstraklasa 2024-25',
 'Poland Ekstraklasa 2025-26',
 'Portugal Primeira Liga 2024-25',
 'Portugal Primeira Liga 2025-26',
 'Portugal Segunda Liga 2024-25',
 'Portugal Segunda Liga 2025-26',
 'Romania SuperLiga 2024-25',
 'Romania SuperLiga 2025-26',
 'Russia Premier League 2024-25',
 'Russia Premier League 2025-26',
 'Scotland Championship 2024-25',
 'Scotland Championship 2025-26',
 'Scotland League One 2024-25',
 'Scotland League One 2025-26',
 'Scotland League Two 2024-25',
 'Scotland League Two 2025-26',
 'Scotland Premiership 2024-25',
 'Scotland Premiership 2025-26',
 'Serbia Prva Liga 2025-26',
 'Serbia Super Liga 2024-25',
 'Serbia Super Liga 2025-26',
 'Slovakia Super Liga 2024-25',
 'Slovakia Super Liga 2025-26',
 'Slovenia Prva Liga 2024-25',
 'Slovenia Prva Liga 2025-26',
 'South Africa PSL 2024-25',
 'South Africa PSL 2025-26',
 'Spain La Liga 2024-25',
 'Spain La Liga 2025-26',
 'Spain Primera Division RFEF 2024-25',
 'Spain Primera Division RFEF 2025-26',
 'Spain Segunda 2024-25',
 'Spain Segunda 2025-26',
 'Sweden Allsvenskan 2025',
 'Switzerland Challenge League 2024-25',
 'Switzerland Challenge League 2025-26',
 'Switzerland Super League 2024-25',
 'Switzerland Super League 2025-26',
 'Turkey Super Lig 2024-25',
 'Turkey Super Lig 2025-26',
 'USA MLS 2025',
 'USA MLS 2026',
 'USA MLS Next Pro 2025',
 'USA MLS Next Pro 2026',
 'USA USL Championship 2025',
 'USA USL Championship 2026',
 'USA USL League 1 2025',
 'USA USL League 1 2026',
 'Ukraine Premier League 2024-25',
 'Ukraine Premier League 2025-26',
 'Uruguay Primera Division 2025',
 'Uruguay Primera Division 2026',
 'Uzbekistan Super League 2025',
 'Uzbekistan Super League 2026',
 'Venezuela Primera Division 2025',
 'Venezuela Primera Division 2026']

In [4]:
# Filter settings used later in code

filter_positions = ["CB", "RCB", "LCB"]
filter_leagues = [
                  #'England Premier League 2024-25'
                  #'England Premier League 2025-26'
                  'England League One 2025-26',
                  'England League Two 2025-26'
                  ]
filter_minutes = 450

# Columns to exclude from the Z-Score Calculation
excluded_columns = ['Player', 'Team', 'Team within selected timeframe', 'Position','Age', 'Market value', 'Contract expires', 'Matches played', 'Minutes played','Birth country', 'Passport country', 'Foot', 'Height', 'Weight', 'On loan','League', 'Main Position']

# Export names
rating_export_name = "CUFC Ratings - CB.csv"

### Calculate Z-Scores and Export Data for Review

In [5]:
# Create filtered df prior to applying the filters
filtered_df = df.copy()

# Apply filters to the filtered df
filtered_df = filtered_df[ filtered_df['League'].isin(filter_leagues) ]             # filter leagues
filtered_df = filtered_df[ filtered_df['Main Position'].isin(filter_positions) ]    # filter position
filtered_df = filtered_df[ filtered_df['Minutes played'] >= filter_minutes ]        # filter minutes played

filtered_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
876,E. Pye,Stockport County,Stockport County,LCB,23.0,450000,30/06/2027,40,4003,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League One 2025-26,LCB
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,"LCB, LB",27.0,300000,30/06/2026,40,3944,1,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League One 2025-26,LCB
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,"RCB, RB",23.0,0,30/06/2027,41,3921,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League One 2025-26,RCB
885,S. Bradley,Lincoln City,Lincoln City,"LCB, CB",34.0,275000,30/06/2027,40,3918,3,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League One 2025-26,LCB
890,O. Casey,Blackpool,Blackpool,"LCB, RCB",25.0,300000,30/06/2026,40,3852,1,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League One 2025-26,LCB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,"CB, LCB",35.0,100000,31/05/2026,6,560,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League Two 2025-26,CB
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,29.0,275000,30/06/2027,6,555,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League Two 2025-26,RCB
19865,P. Chinedu,Barnet,Barnet,"LCB, LB",19.0,0,30/06/2027,13,529,1,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
19870,C. Masterson,Gillingham,Gillingham,"LCB, CB, RCB",27.0,250000,30/06/2026,8,518,2,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,"LCB, RCB",19.0,0,31/05/2026,7,499,0,...,NaN,NaN,0.0,0.0,0.0,0.0,0,0.0,England League Two 2025-26,LCB

In [6]:
# Calculate the z-scores for all metric columns

z_score_df = filtered_df.copy() # create a new df that is a copy of the filtered df

columns_to_zscore = [col for col in filtered_df.columns if col not in excluded_columns] # creates a list of all columns that are not in the excluded list, i.e. a list of columns to convert into z-scores

z_score_df[columns_to_zscore] = z_score_df[columns_to_zscore].apply(zscore) # takes the metric columns subset of the filtered_df, calculates the z-score for each data point and replaces the absolute value with the z-score

# the apply function works column-wise by default - i.e. for each column, calculate the z-score for each value in the column
# then it is assign back into the original filtered_df. This only works because the output (z-scores) are the same length as the input (filtered_df)

# Invert Z-Scores for specific columns
columns_to_invert = ["Yellow cards per 90", "Red cards per 90", "Fouls per 90"]
z_score_df[columns_to_invert] = z_score_df[columns_to_invert] * -1

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
876,E. Pye,Stockport County,Stockport County,LCB,23.0,450000,30/06/2027,40,4003,-0.845154,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League One 2025-26,LCB
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,"LCB, LB",27.0,300000,30/06/2026,40,3944,0.000000,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League One 2025-26,LCB
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,"RCB, RB",23.0,0,30/06/2027,41,3921,-0.845154,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League One 2025-26,RCB
885,S. Bradley,Lincoln City,Lincoln City,"LCB, CB",34.0,275000,30/06/2027,40,3918,1.690309,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League One 2025-26,LCB
890,O. Casey,Blackpool,Blackpool,"LCB, RCB",25.0,300000,30/06/2026,40,3852,0.000000,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League One 2025-26,LCB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,"CB, LCB",35.0,100000,31/05/2026,6,560,-0.845154,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League Two 2025-26,CB
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,29.0,275000,30/06/2027,6,555,-0.845154,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League Two 2025-26,RCB
19865,P. Chinedu,Barnet,Barnet,"LCB, LB",19.0,0,30/06/2027,13,529,0.000000,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League Two 2025-26,LCB
19870,C. Masterson,Gillingham,Gillingham,"LCB, CB, RCB",27.0,250000,30/06/2026,8,518,0.845154,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League Two 2025-26,LCB
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,"LCB, RCB",19.0,0,31/05/2026,7,499,-0.845154,...,NaN,NaN,-0.21261,-0.165663,-0.219729,-0.150536,-0.086929,-0.086929,England League Two 2025-26,LCB

In [7]:
# Function to normalize the data to a [0, 1] range
def NormalizeData(data):
    # Subtract the minimum value from each element and divide by the range
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Iterate over the specified columns (columns_to_zscore) to normalize them
for column in columns_to_zscore:
    # Apply the NormalizeData function to scale the column values
    z_score_df[column] = NormalizeData(z_score_df[column])

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
876,E. Pye,Stockport County,Stockport County,LCB,23.0,450000,30/06/2027,40,4003,0.000000,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League One 2025-26,LCB
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,"LCB, LB",27.0,300000,30/06/2026,40,3944,0.166667,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League One 2025-26,LCB
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,"RCB, RB",23.0,0,30/06/2027,41,3921,0.000000,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League One 2025-26,RCB
885,S. Bradley,Lincoln City,Lincoln City,"LCB, CB",34.0,275000,30/06/2027,40,3918,0.500000,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League One 2025-26,LCB
890,O. Casey,Blackpool,Blackpool,"LCB, RCB",25.0,300000,30/06/2026,40,3852,0.166667,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League One 2025-26,LCB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,"CB, LCB",35.0,100000,31/05/2026,6,560,0.000000,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League Two 2025-26,CB
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,29.0,275000,30/06/2027,6,555,0.000000,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League Two 2025-26,RCB
19865,P. Chinedu,Barnet,Barnet,"LCB, LB",19.0,0,30/06/2027,13,529,0.166667,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League Two 2025-26,LCB
19870,C. Masterson,Gillingham,Gillingham,"LCB, CB, RCB",27.0,250000,30/06/2026,8,518,0.333333,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League Two 2025-26,LCB
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,"LCB, RCB",19.0,0,31/05/2026,7,499,0.000000,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,England League Two 2025-26,LCB

### Attribute Definition and Calculation

In [8]:
# Create new rating columns in a batch
new_columns = {
                # Template line: 'REPLACE Rating': z_score_df['REPLACE'] * 0,

                # Defending - 40%
                'Defensive duels won % Rating':               z_score_df['Defensive duels won, %']                 * 0.35,
                'PAdj Interceptions Rating':                  z_score_df['PAdj Interceptions']                     * 0.20,
                'PAdj Sliding tackles Rating':                z_score_df['PAdj Sliding tackles']                   * 0.20,
                'Successful defensive actions per 90 Rating': z_score_df['Successful defensive actions per 90']    * 0.125,
                'Shots blocked per 90 Rating':                z_score_df['Shots blocked per 90']                   * 0.125,
                
                # Aerial - 30%
                'Aerial duels won % Rating':   z_score_df['Aerial duels won, %'] * 0.60,
                'Aerial duels per 90 Rating':  z_score_df['Aerial duels per 90'] * 0.40,
                
                # Pass Retention - 10%
                'Accurate short passes % Rating':   z_score_df['Accurate short / medium passes, %'] * 0.50,
                'Short passes per 90 Rating':       z_score_df['Short / medium passes per 90']      * 0.30,
                'Received passes per 90 Rating':    z_score_df['Received passes per 90']            * 0.20,

                # Pass Progression - 5%
                'Progressive passes per 90 Rating':        z_score_df['Progressive passes per 90']         * 0.40,
                'Accurate progressive passes % Rating':    z_score_df['Accurate progressive passes, %']    * 0.60,
                
                # Discipline 15%
                'Fouls per 90 Rating':         z_score_df['Fouls per 90']     * 0.50,
                'Yellows per 90 Rating':  z_score_df['Yellow cards per 90']   * 0.30,
                'Reds per 90 Rating':     z_score_df['Red cards per 90']      * 0.20
                }

# Create the new attribute columns using the above ratings columns
# Template line: new_columns['REPLACE Att'] = new_columns['REPLACE'] + new_columns['REPLACE'] + new_columns['REPLACE'] + new_columns['REPLACE']
new_columns['Defending Att'] = new_columns['Defensive duels won % Rating'] + new_columns['PAdj Interceptions Rating'] + new_columns['PAdj Sliding tackles Rating'] + new_columns['Successful defensive actions per 90 Rating'] + new_columns['Shots blocked per 90 Rating']
new_columns['Aerial Att']    = new_columns['Aerial duels won % Rating'] + new_columns['Aerial duels per 90 Rating']
new_columns['Pass Retention Att']   = new_columns['Accurate short passes % Rating'] + new_columns['Short passes per 90 Rating'] + new_columns['Received passes per 90 Rating']
new_columns['Pass Progression Att'] = new_columns['Progressive passes per 90 Rating'] + new_columns['Accurate progressive passes % Rating']
new_columns['Discipline Att']     = new_columns['Fouls per 90 Rating'] + new_columns['Yellows per 90 Rating'] + new_columns['Reds per 90 Rating']

# Add all new columns to the DataFrame at once
z_score_df = pd.concat([z_score_df, pd.DataFrame(new_columns)], axis=1)

# Create a fresh copy of the df to avoid issues if re-running cells
z_score_df = z_score_df.copy()
z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Progressive passes per 90 Rating,Accurate progressive passes % Rating,Fouls per 90 Rating,Yellows per 90 Rating,Reds per 90 Rating,Defending Att,Aerial Att,Pass Retention Att,Pass Progression Att,Discipline Att
876,E. Pye,Stockport County,Stockport County,LCB,23.0,450000,30/06/2027,40,4003,0.000000,...,0.234902,0.523043,0.277778,0.208475,0.200,0.506107,0.581019,0.751951,0.757945,0.686252
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,"LCB, LB",27.0,300000,30/06/2026,40,3944,0.166667,...,0.212941,0.529174,0.287037,0.208475,0.200,0.355863,0.591872,0.928777,0.742115,0.695512
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,"RCB, RB",23.0,0,30/06/2027,41,3921,0.000000,...,0.204314,0.411932,0.265432,0.254237,0.200,0.326923,0.243214,0.538553,0.616246,0.719669
885,S. Bradley,Lincoln City,Lincoln City,"LCB, CB",34.0,275000,30/06/2027,40,3918,0.500000,...,0.066667,0.414231,0.364198,0.264407,0.184,0.441500,0.585059,0.544386,0.480898,0.812604
890,O. Casey,Blackpool,Blackpool,"LCB, RCB",25.0,300000,30/06/2026,40,3852,0.166667,...,0.048235,0.348331,0.246914,0.228814,0.200,0.462916,0.599767,0.651121,0.396566,0.675727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,"CB, LCB",35.0,100000,31/05/2026,6,560,0.000000,...,0.163922,0.392556,0.157407,0.137288,0.200,0.478215,0.581832,0.322548,0.556478,0.494696
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,29.0,275000,30/06/2027,6,555,0.000000,...,0.198431,0.452217,0.456790,0.300000,0.200,0.676376,0.488890,0.631284,0.650648,0.956790
19865,P. Chinedu,Barnet,Barnet,"LCB, LB",19.0,0,30/06/2027,13,529,0.166667,...,0.155686,0.378325,0.135802,0.213559,0.200,0.800846,0.394616,0.277789,0.534011,0.549362
19870,C. Masterson,Gillingham,Gillingham,"LCB, CB, RCB",27.0,250000,30/06/2026,8,518,0.333333,...,0.005490,0.259332,0.395062,0.300000,0.200,0.347208,0.540695,0.598632,0.264822,0.895062
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,"LCB, RCB",19.0,0,31/05/2026,7,499,0.000000,...,0.053725,0.000000,0.000000,0.025424,0.200,0.710519,0.853204,0.262905,0.053725,0.225424

In [9]:
# Create new df containing absolute values to append onto final ratings df later
absolute_columns = [# For join
                    'Player',
                    'Team within selected timeframe',
                    
                    # Defending
                    'Defensive duels won, %',
                    'PAdj Interceptions',
                    'PAdj Sliding tackles',
                    'Successful defensive actions per 90',
                    'Shots blocked per 90',
                    
                    # Aerial
                    'Aerial duels won, %',
                    'Aerial duels per 90',
                    
                    # Pass Retention
                    'Accurate short / medium passes, %',
                    'Short / medium passes per 90',
                    'Received passes per 90',
                    
                    # Pass Progression
                    'Progressive passes per 90',
                    'Accurate progressive passes, %',
                    
                    # Discipline
                    'Fouls per 90',
                    'Yellow cards per 90',
                    'Red cards per 90',

                    # Set Pieces
                    'Free kicks per 90',
                    'Direct free kicks per 90',
                    'Direct free kicks on target, %',
                    'Corners per 90',
                    
                    ]
absolute_values = filtered_df[absolute_columns].copy()

absolute_values

,Player,Team within selected timeframe,"Defensive duels won, %",PAdj Interceptions,PAdj Sliding tackles,Successful defensive actions per 90,Shots blocked per 90,"Aerial duels won, %",Aerial duels per 90,"Accurate short / medium passes, %",...,Received passes per 90,Progressive passes per 90,"Accurate progressive passes, %",Fouls per 90,Yellow cards per 90,Red cards per 90,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90
876,E. Pye,Stockport County,73.45,8.37,0.34,10.61,0.54,62.75,6.88,89.82,...,33.14,9.85,71.92,0.90,0.18,0.00,0.0,0.0,0.0,0.0
880,G. Johnston,Bolton Wanderers,62.62,7.43,0.46,7.64,0.52,62.82,7.12,93.47,...,45.59,9.29,72.48,0.87,0.18,0.00,0.0,0.0,0.0,0.0
883,I. Ogundere,AFC Wimbledon,65.11,5.83,0.03,9.09,0.69,45.60,4.43,84.70,...,21.53,9.07,61.77,0.94,0.09,0.00,0.0,0.0,0.0,0.0
885,S. Bradley,Lincoln City,73.17,7.13,0.20,7.86,0.90,60.06,7.88,88.42,...,16.22,5.56,61.98,0.62,0.07,0.02,0.0,0.0,0.0,0.0
890,O. Casey,Blackpool,73.46,7.17,0.16,9.81,0.79,67.06,5.89,90.52,...,22.80,5.09,55.96,1.00,0.14,0.00,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Cheltenham Town,71.43,6.22,0.89,9.96,0.48,54.10,9.80,77.67,...,11.25,8.04,60.00,1.29,0.32,0.00,0.0,0.0,0.0,0.0
19861,S. Lavelle,Grimsby Town,78.13,11.32,0.57,10.86,0.97,54.35,7.46,89.50,...,20.59,8.92,65.45,0.32,0.00,0.00,0.0,0.0,0.0,0.0
19865,P. Chinedu,Barnet,83.78,10.00,1.94,11.57,0.34,44.90,8.34,70.87,...,17.01,7.83,58.70,1.36,0.17,0.00,0.0,0.0,0.0,0.0
19870,C. Masterson,Gillingham,76.92,4.90,0.00,6.25,0.52,56.52,7.99,89.57,...,18.42,4.00,47.83,0.52,0.00,0.00,0.0,0.0,0.0,0.0
19878,J. Mazionis,Cheltenham Town,77.14,9.81,1.12,11.90,1.08,75.00,9.38,75.27,...,5.59,5.23,24.14,1.80,0.54,0.00,0.0,0.0,0.0,0.0

In [10]:
# Creating the new DataFrame 'ratings' with the specified columns
ratings_columns = [
                    "Player", "Team", "Team within selected timeframe", "Main Position", "Position", "League",
                    "Age", "Market value", "Contract expires", "On loan", "Minutes played",
                    
                    # New Att columns created earlier:
                    "Defending Att", "Aerial Att", "Pass Retention Att", "Pass Progression Att", "Discipline Att"
                    ]

ratings = z_score_df[ratings_columns].copy()

ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Defending Att,Aerial Att,Pass Retention Att,Pass Progression Att,Discipline Att
876,E. Pye,Stockport County,Stockport County,LCB,LCB,England League One 2025-26,23.0,450000,30/06/2027,no,4003,0.506107,0.581019,0.751951,0.757945,0.686252
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,LCB,"LCB, LB",England League One 2025-26,27.0,300000,30/06/2026,no,3944,0.355863,0.591872,0.928777,0.742115,0.695512
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,RCB,"RCB, RB",England League One 2025-26,23.0,0,30/06/2027,no,3921,0.326923,0.243214,0.538553,0.616246,0.719669
885,S. Bradley,Lincoln City,Lincoln City,LCB,"LCB, CB",England League One 2025-26,34.0,275000,30/06/2027,no,3918,0.441500,0.585059,0.544386,0.480898,0.812604
890,O. Casey,Blackpool,Blackpool,LCB,"LCB, RCB",England League One 2025-26,25.0,300000,30/06/2026,no,3852,0.462916,0.599767,0.651121,0.396566,0.675727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,CB,"CB, LCB",England League Two 2025-26,35.0,100000,31/05/2026,no,560,0.478215,0.581832,0.322548,0.556478,0.494696
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,RCB,England League Two 2025-26,29.0,275000,30/06/2027,no,555,0.676376,0.488890,0.631284,0.650648,0.956790
19865,P. Chinedu,Barnet,Barnet,LCB,"LCB, LB",England League Two 2025-26,19.0,0,30/06/2027,no,529,0.800846,0.394616,0.277789,0.534011,0.549362
19870,C. Masterson,Gillingham,Gillingham,LCB,"LCB, CB, RCB",England League Two 2025-26,27.0,250000,30/06/2026,no,518,0.347208,0.540695,0.598632,0.264822,0.895062
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,LCB,"LCB, RCB",England League Two 2025-26,19.0,0,31/05/2026,no,499,0.710519,0.853204,0.262905,0.053725,0.225424

In [11]:
# Normalise the data again after we have created attributes

# Ensure a copy of the DataFrame to prevent unintended changes to the original data
norm_ratings = ratings.copy()

# Select columns that end with the word "Att"
columns_to_normalize = [col for col in norm_ratings.columns if col.endswith('Att')]

# Iterate over the selected columns and apply normalization
for column in columns_to_normalize:

    # Apply the NormalizeData function to scale the column
    norm_ratings[column] = NormalizeData(norm_ratings[column])

norm_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Defending Att,Aerial Att,Pass Retention Att,Pass Progression Att,Discipline Att
876,E. Pye,Stockport County,Stockport County,LCB,LCB,England League One 2025-26,23.0,450000,30/06/2027,no,4003,0.537833,0.612971,0.767901,0.792714,0.619519
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,LCB,"LCB, LB",England League One 2025-26,27.0,300000,30/06/2026,no,3944,0.302243,0.626370,0.948478,0.774894,0.630748
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,RCB,"RCB, RB",England League One 2025-26,23.0,0,30/06/2027,no,3921,0.256864,0.195967,0.549977,0.633208,0.660044
885,S. Bradley,Lincoln City,Lincoln City,LCB,"LCB, CB",England League One 2025-26,34.0,275000,30/06/2027,no,3918,0.436526,0.617959,0.555934,0.480852,0.772746
890,O. Casey,Blackpool,Blackpool,LCB,"LCB, RCB",England League One 2025-26,25.0,300000,30/06/2026,no,3852,0.470108,0.636114,0.664933,0.385923,0.606755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,CB,"CB, LCB",England League Two 2025-26,35.0,100000,31/05/2026,no,560,0.494098,0.613975,0.329390,0.565930,0.387218
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,RCB,England League Two 2025-26,29.0,275000,30/06/2027,no,555,0.804824,0.499242,0.644675,0.671934,0.947599
19865,P. Chinedu,Barnet,Barnet,LCB,"LCB, LB",England League Two 2025-26,19.0,0,30/06/2027,no,529,1.000000,0.382866,0.283681,0.540640,0.453512
19870,C. Masterson,Gillingham,Gillingham,LCB,"LCB, CB, RCB",England League Two 2025-26,27.0,250000,30/06/2026,no,518,0.288672,0.563194,0.611331,0.237624,0.872742
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,LCB,"LCB, RCB",England League Two 2025-26,19.0,0,31/05/2026,no,499,0.858362,0.948971,0.268482,0.000000,0.060673

### Weighting the Attributes to Create an Overall Rating

In [12]:
# Weight the overall attributes in terms of importance 
weighted_ratings = norm_ratings.copy()

#Weight the overall ratings
weighted_ratings['Defending Att'] =        weighted_ratings['Defending Att']        * 0.40
weighted_ratings['Aerial Att'] =           weighted_ratings['Aerial Att']           * 0.30
weighted_ratings['Pass Retention Att'] =   weighted_ratings['Pass Retention Att']   * 0.10
weighted_ratings['Pass Progression Att'] = weighted_ratings['Pass Progression Att'] * 0.05
weighted_ratings['Discipline Att'] =       weighted_ratings['Discipline Att']       * 0.15

weighted_ratings['CB Rating'] = ( weighted_ratings['Defending Att'] 
                                + weighted_ratings['Aerial Att'] 
                                + weighted_ratings['Pass Retention Att']
                                + weighted_ratings['Pass Progression Att'] 
                                + weighted_ratings['Discipline Att'] 
                                )

weighted_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Defending Att,Aerial Att,Pass Retention Att,Pass Progression Att,Discipline Att,CB Rating
876,E. Pye,Stockport County,Stockport County,LCB,LCB,England League One 2025-26,23.0,450000,30/06/2027,no,4003,0.215133,0.183891,0.076790,0.039636,0.092928,0.608378
880,G. Johnston,Bolton Wanderers,Bolton Wanderers,LCB,"LCB, LB",England League One 2025-26,27.0,300000,30/06/2026,no,3944,0.120897,0.187911,0.094848,0.038745,0.094612,0.537013
883,I. Ogundere,AFC Wimbledon,AFC Wimbledon,RCB,"RCB, RB",England League One 2025-26,23.0,0,30/06/2027,no,3921,0.102746,0.058790,0.054998,0.031660,0.099007,0.347201
885,S. Bradley,Lincoln City,Lincoln City,LCB,"LCB, CB",England League One 2025-26,34.0,275000,30/06/2027,no,3918,0.174611,0.185388,0.055593,0.024043,0.115912,0.555546
890,O. Casey,Blackpool,Blackpool,LCB,"LCB, RCB",England League One 2025-26,25.0,300000,30/06/2026,no,3852,0.188043,0.190834,0.066493,0.019296,0.091013,0.555680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19860,S. Bennett,Weston-super-Mare,Cheltenham Town,CB,"CB, LCB",England League Two 2025-26,35.0,100000,31/05/2026,no,560,0.197639,0.184193,0.032939,0.028296,0.058083,0.501150
19861,S. Lavelle,Grimsby Town,Grimsby Town,RCB,RCB,England League Two 2025-26,29.0,275000,30/06/2027,no,555,0.321930,0.149773,0.064467,0.033597,0.142140,0.711906
19865,P. Chinedu,Barnet,Barnet,LCB,"LCB, LB",England League Two 2025-26,19.0,0,30/06/2027,no,529,0.400000,0.114860,0.028368,0.027032,0.068027,0.638287
19870,C. Masterson,Gillingham,Gillingham,LCB,"LCB, CB, RCB",England League Two 2025-26,27.0,250000,30/06/2026,no,518,0.115469,0.168958,0.061133,0.011881,0.130911,0.488353
19878,J. Mazionis,Cheltenham Town,Cheltenham Town,LCB,"LCB, RCB",England League Two 2025-26,19.0,0,31/05/2026,no,499,0.343345,0.284691,0.026848,0.000000,0.009101,0.663985

In [13]:
# Final time to normalise, this time for the overall rating 

# Ensure a copy of the DataFrame to prevent unintended changes
final_ratings = weighted_ratings.copy()

# Select the attribute and rating columns in the DataFrame
columns_to_normalize = [col for col in final_ratings.columns if col.endswith('Att') or col.endswith('Rating')]

# Normalise the attribute and rating columns
for column in columns_to_normalize:
    final_ratings[column] = NormalizeData(final_ratings[column]) # function defined earlier

# Multiply columns ending with 'Att' or 'Rating' by 100 and round to 2 decimal places
final_ratings[columns_to_normalize] = (final_ratings[columns_to_normalize] * 100).round(2)

# Sort the DataFrame by the last column in descending order
rating_column = [col for col in final_ratings.columns if col.endswith('Rating')]
final_ratings.sort_values(by=rating_column, ascending=False, inplace=True)

# Merge the absolute values
final_ratings = final_ratings.merge(absolute_values,on=['Player','Team within selected timeframe'], how='left')

# Reset the index of the sorted DataFrame to ensure a clean, sequential index
final_ratings.reset_index(drop=True, inplace=True)

# Export the ratings to CSV
final_ratings.to_csv(rating_export_name, index=False)
print(f"Ratings exported at {datetime.now().strftime('%d-%m-%Y %H:%M')}")

final_ratings

Ratings exported at 18-05-2026 16:36

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,...,Received passes per 90,Progressive passes per 90,"Accurate progressive passes, %",Fouls per 90,Yellow cards per 90,Red cards per 90,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90
0,R. Tafazolli,Swindon Town,Swindon Town,LCB,"LCB, CB",England League Two 2025-26,34.0,175000,30/06/2026,no,...,17.08,8.38,51.92,0.43,0.16,0.00,0.00,0.00,0.0,0.00
1,A. O'Connor,Harrogate Town,Harrogate Town,RCB,"RCB, CB",England League Two 2025-26,33.0,200000,30/06/2027,no,...,15.02,8.00,59.72,0.68,0.27,0.00,0.04,0.04,100.0,0.00
2,C. Forino-Joseph,Bolton Wanderers,Bolton Wanderers,RCB,"RCB, LCB, CB",England League One 2025-26,25.0,0,30/06/2027,no,...,31.44,5.02,60.83,0.59,0.17,0.00,0.00,0.00,0.0,0.00
3,S. Negru,Tranmere Rovers,Tranmere Rovers,RCB,"RCB, LCB, CB",England League Two 2025-26,23.0,0,31/05/2026,no,...,15.83,8.01,57.85,0.46,0.00,0.00,0.00,0.00,0.0,0.00
4,S. Lavelle,Grimsby Town,Grimsby Town,RCB,RCB,England League Two 2025-26,29.0,275000,30/06/2027,no,...,20.59,8.92,65.45,0.32,0.00,0.00,0.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,J. Hunt,Wigan Athletic,Wigan Athletic,RCB,"RCB, RB, RWB",England League One 2025-26,35.0,100000,30/06/2026,no,...,30.66,12.63,64.04,0.57,0.14,0.00,0.00,0.00,0.0,0.00
238,D. Love,Accrington Stanley,Accrington Stanley,RCB,"RCB, RWB",England League Two 2025-26,31.0,175000,30/06/2028,no,...,21.94,10.56,72.10,0.86,0.40,0.03,0.20,0.03,0.0,0.10
239,F. Sass,Accrington Stanley,Accrington Stanley,LCB,"LCB, LB, LWB",England League Two 2025-26,24.0,0,NaN,no,...,15.88,8.44,58.55,1.22,0.17,0.00,0.00,0.00,0.0,0.06
240,A. MacDonald,Barrow,Barrow,RCB,"RCB, CB",England League Two 2025-26,33.0,300000,NaN,no,...,9.00,5.92,58.33,0.99,0.12,0.00,0.00,0.00,0.0,0.00
241,B. Webster,Bromley,Bromley,CB,"CB, LCB",England League Two 2025-26,38.0,0,30/06/2026,no,...,6.27,5.67,57.89,1.04,0.30,0.15,0.15,0.00,0.0,0.15