# Player Attribute Ratings System

### Setup and Inputs

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
from datetime import datetime

In [2]:
# Load the latest Wyscout dataset available

df = pd.read_csv("Wyscout_League_Export 2026-04-14.csv")

In [3]:
# Create list of unique leagues within dataset

list_unique_leagues = list( sorted( df['League'].unique() ) )
list_unique_leagues

['Albania Superiore League 2024-25',
 'Albania Superiore League 2025-26',
 'Argentina Primera Division 2025',
 'Argentina Primera Division 2026',
 'Australia A-League 2024-25',
 'Australia A-League 2025-26',
 'Austria Bundesliga 2024-25',
 'Austria Bundesliga 2025-26',
 'Belgium First Division A 2024-25',
 'Belgium First Division A 2025-26',
 'Belgium First Division B 2024-25',
 'Belgium First Division B 2025-26',
 'Bolivia Primera Division 2025',
 'Bosnia Premijer Liga 2024-25',
 'Bosnia Premijer Liga 2025-26',
 'Brazil Serie A 2025',
 'Brazil Serie A 2026',
 'Brazil Serie B 2025',
 'Brazil Serie B 2026',
 'Bulgaria First League 2024-25',
 'Bulgaria First League 2025-26',
 'Canada Premier League 2025',
 'Chile Primera Division 2025',
 'Chile Primera Division 2026',
 'China Super League 2025',
 'China Super League 2026',
 'Colombia Primera A 2025',
 'Colombia Primera A 2026',
 'Costa Rica Primera Division 2024-25',
 'Costa Rica Primera Division 2025-26',
 'Croatia 1.HNL 2024-25',
 'Croatia 1.HNL 2025-26',
 'Cyprus First Division 2024-25',
 'Cyprus First Division 2025-26',
 'Czech Fortuna Liga 2024-25',
 'Czech Fortuna Liga 2025-26',
 'Denmark 1st Division 2024-25',
 'Denmark 1st Division 2025-26',
 'Denmark Superliga 2024-25',
 'Denmark Superliga 2025-26',
 'Ecuador Serie A 2025',
 'Ecuador Serie A 2026',
 'Egypt Premier League 2024-25',
 'Egypt Premier League 2025-26',
 'England Championship 2024-25',
 'England Championship 2025-26',
 'England League One 2024-25',
 'England League One 2025-26',
 'England League Two 2024-25',
 'England League Two 2025-26',
 'England National League 2024-25',
 'England National League 2025-26',
 'England National League North South 2024-25',
 'England National League North South 2025-26',
 'England Premier League 2024-25',
 'England Premier League 2025-26',
 'Estonia Meistriliiga 2025',
 'Estonia Meistriliiga 2026',
 'Finland Veikkausliiga 2025',
 'France Championnat National 2024-25',
 'France Championnat National 2025-26',
 'France Ligue 1 2024-25',
 'France Ligue 1 2025-26',
 'France Ligue 2 2024-25',
 'France Ligue 2 2025-26',
 'Georgia Erovnuli Liga 2025',
 'Georgia Erovnuli Liga 2026',
 'Germany 2. Bundesliga 2024-25',
 'Germany 2. Bundesliga 2025-26',
 'Germany 3. Liga 2024-25',
 'Germany 3. Liga 2025-26',
 'Germany Bundesliga 2024-25',
 'Germany Bundesliga 2025-26',
 'Greece Super League 2024-25',
 'Greece Super League 2025-26',
 'Hungary NB1 2024-25',
 'Hungary NB1 2025-26',
 'Indonesia Liga 1 2024-25',
 'Indonesia Liga 1 2025-26',
 'Ireland First Division 2025',
 'Ireland First Division 2026',
 'Ireland Premier Division 2025',
 'Ireland Premier Division 2026',
 "Israel Ligat Ha'Al 2024-25",
 "Israel Ligat Ha'Al 2025-26",
 'Italy Campionato Primavera 1 2024-25',
 'Italy Campionato Primavera 1 2025-26',
 'Italy Serie A 2024-25',
 'Italy Serie A 2025-26',
 'Italy Serie B 2024-25',
 'Italy Serie B 2025-26',
 'Japan J1 100 Year Vision League 2026',
 'Japan J1-League 2025',
 'Japan J2-J3 100 Year Vision League 2026',
 'Japan J2-League 2025',
 'Kazakhstan Premier League 2025',
 'Kazakhstan Premier League 2026',
 'Korea K-League 1 2025',
 'Korea K-League 1 2026',
 'Korea K-League 2 2025',
 'Korea K-League 2 2026',
 'Latvia Virsliga 2025',
 'Latvia Virsliga 2026',
 'Malaysia Super League 2024-25',
 'Malaysia Super League 2025-26',
 'Mexico Liga MX 2024-25',
 'Mexico Liga MX 2025-26',
 'Mexico Liga de Expansion 2024-25',
 'Mexico Liga de Expansion 2025-26',
 'Morocco Botola Pro 2024-25',
 'Morocco Botola Pro 2025-26',
 'Netherlands Eerste Divisie 2024-25',
 'Netherlands Eerste Divisie 2025-26',
 'Netherlands Eredivisie 2024-25',
 'Netherlands Eredivisie 2025-26',
 'Northern Ireland Premiership 2024-25',
 'Northern Ireland Premiership 2025-26',
 'Norway Eliteserien 2025',
 'Norway Eliteserien 2026',
 'Norway First Division 2025',
 'Paraguay Primera Division 2025',
 'Paraguay Primera Division 2026',
 'Peru Primera Division 2025',
 'Peru Primera Division 2026',
 'Poland 1 Liga 2024-25',
 'Poland 1 Liga 2025-26',
 'Poland Ekstraklasa 2024-25',
 'Poland Ekstraklasa 2025-26',
 'Portugal Primeira Liga 2024-25',
 'Portugal Primeira Liga 2025-26',
 'Portugal Segunda Liga 2024-25',
 'Portugal Segunda Liga 2025-26',
 'Romania SuperLiga 2024-25',
 'Romania SuperLiga 2025-26',
 'Russia Premier League 2024-25',
 'Russia Premier League 2025-26',
 'Scotland Championship 2024-25',
 'Scotland Championship 2025-26',
 'Scotland League One 2024-25',
 'Scotland League One 2025-26',
 'Scotland League Two 2024-25',
 'Scotland League Two 2025-26',
 'Scotland Premiership 2024-25',
 'Scotland Premiership 2025-26',
 'Serbia Prva Liga 2025-26',
 'Serbia Super Liga 2024-25',
 'Serbia Super Liga 2025-26',
 'Slovakia Super Liga 2024-25',
 'Slovakia Super Liga 2025-26',
 'Slovenia Prva Liga 2024-25',
 'Slovenia Prva Liga 2025-26',
 'South Africa PSL 2024-25',
 'South Africa PSL 2025-26',
 'Spain La Liga 2024-25',
 'Spain La Liga 2025-26',
 'Spain Primera Division RFEF 2024-25',
 'Spain Primera Division RFEF 2025-26',
 'Spain Segunda 2024-25',
 'Spain Segunda 2025-26',
 'Sweden Allsvenskan 2025',
 'Switzerland Challenge League 2024-25',
 'Switzerland Challenge League 2025-26',
 'Switzerland Super League 2024-25',
 'Switzerland Super League 2025-26',
 'Turkey Super Lig 2024-25',
 'Turkey Super Lig 2025-26',
 'USA MLS 2025',
 'USA MLS 2026',
 'USA MLS Next Pro 2025',
 'USA MLS Next Pro 2026',
 'USA USL Championship 2025',
 'USA USL Championship 2026',
 'USA USL League 1 2025',
 'USA USL League 1 2026',
 'Ukraine Premier League 2024-25',
 'Ukraine Premier League 2025-26',
 'Uruguay Primera Division 2025',
 'Uruguay Primera Division 2026',
 'Uzbekistan Super League 2025',
 'Uzbekistan Super League 2026',
 'Venezuela Primera Division 2025',
 'Venezuela Primera Division 2026']

In [4]:
# Filter settings used later in code

filter_positions = ["RW", "LW", "AMF", "RAMF", "LAMF", "RWF", "LWF"]
filter_leagues = [
                  #'England Premier League 2025-26'
                  'England League One 2025-26',
                  'England League Two 2025-26'
                  ]
filter_minutes = 450

# Columns to exclude from the Z-Score Calculation
excluded_columns = ['Player', 'Team', 'Team within selected timeframe', 'Position','Age', 'Market value', 'Contract expires', 'Matches played', 'Minutes played','Birth country', 'Passport country', 'Foot', 'Height', 'Weight', 'On loan','League', 'Main Position']

# Export names
rating_export_name = "CUFC Ratings - Wingers.csv"

### Calculate Z-Scores and Export Data for Review

In [5]:
# Create filtered df prior to applying the filters
filtered_df = df.copy()

# Apply filters to the filtered df
filtered_df = filtered_df[ filtered_df['League'].isin(filter_leagues) ]             # filter leagues
filtered_df = filtered_df[ filtered_df['Main Position'].isin(filter_positions) ]    # filter position
filtered_df = filtered_df[ filtered_df['Minutes played'] >= filter_minutes ]        # filter minutes played

filtered_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,"RW, RAMF, RWB",28.0,300000,30/06/2027,39,3593,8,...,NaN,NaN,0.95,0.08,0.0,1.45,4,100.0,England League One 2025-26,RW
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,"RAMF, CF, LAMF",29.0,500000,NaN,40,3511,10,...,NaN,NaN,0.00,0.00,0.0,0.00,0,0.0,England League One 2025-26,RAMF
931,J. Diamond,Stockport County,Stockport County,"AMF, RWB",26.0,350000,30/06/2027,40,3215,6,...,NaN,NaN,0.03,0.00,0.0,0.17,0,0.0,England League One 2025-26,AMF
932,M. Harness,Huddersfield Town,Huddersfield Town,"AMF, RAMF, RCMF",30.0,800000,30/06/2028,40,3207,5,...,NaN,NaN,0.20,0.00,0.0,1.01,0,0.0,England League One 2025-26,AMF
940,C. Wright,Wigan Athletic,Wigan Athletic,"AMF, LCMF",25.0,700000,30/06/2026,37,3149,5,...,NaN,NaN,0.00,0.00,0.0,0.09,0,0.0,England League One 2025-26,AMF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,"AMF, RW, DMF",25.0,0,30/06/2026,13,497,0,...,NaN,NaN,1.63,0.18,0.0,2.54,0,0.0,England League Two 2025-26,AMF
19881,L. Cirino,Gillingham,Gillingham,"LAMF, LWB, LB",23.0,0,30/06/2026,12,492,1,...,NaN,NaN,0.00,0.00,0.0,0.91,0,0.0,England League Two 2025-26,LAMF
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,"RAMF, RW",26.0,325000,30/06/2027,12,482,0,...,NaN,NaN,0.19,0.19,0.0,0.00,0,0.0,England League Two 2025-26,RAMF
19890,C. Deeming,Cheltenham Town,Cheltenham Town,"RW, AMF, LCMF",19.0,0,30/06/2027,14,460,0,...,NaN,NaN,0.59,0.20,0.0,2.15,0,0.0,England League Two 2025-26,RW
19891,E. Sutton,Harrogate Town,Harrogate Town,"LAMF, LW, RWB",19.0,0,31/05/2026,8,456,1,...,NaN,NaN,0.00,0.00,0.0,0.00,0,0.0,England League Two 2025-26,LAMF

In [6]:
# Calculate the z-scores for all metric columns

z_score_df = filtered_df.copy() # create a new df that is a copy of the filtered df

columns_to_zscore = [col for col in filtered_df.columns if col not in excluded_columns] # creates a list of all columns that are not in the excluded list, i.e. a list of columns to convert into z-scores

z_score_df[columns_to_zscore] = z_score_df[columns_to_zscore].apply(zscore) # takes the metric columns subset of the filtered_df, calculates the z-score for each data point and replaces the absolute value with the z-score

# the apply function works column-wise by default - i.e. for each column, calculate the z-score for each value in the column
# then it is assign back into the original filtered_df. This only works because the output (z-scores) are the same length as the input (filtered_df)

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,"RW, RAMF, RWB",28.0,300000,30/06/2027,39,3593,1.679339,...,NaN,NaN,1.565220,0.277052,-0.399827,0.879901,5.311099,3.229805,England League One 2025-26,RW
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,"RAMF, CF, LAMF",29.0,500000,NaN,40,3511,2.382921,...,NaN,NaN,-0.599203,-0.542246,-0.399827,-0.719022,-0.287286,-0.327661,England League One 2025-26,RAMF
931,J. Diamond,Stockport County,Stockport County,"AMF, RWB",26.0,350000,30/06/2027,40,3215,0.975757,...,NaN,NaN,-0.530853,-0.542246,-0.399827,-0.531562,-0.287286,-0.327661,England League One 2025-26,AMF
932,M. Harness,Huddersfield Town,Huddersfield Town,"AMF, RAMF, RCMF",30.0,800000,30/06/2028,40,3207,0.623966,...,NaN,NaN,-0.143535,-0.542246,-0.399827,0.394711,-0.287286,-0.327661,England League One 2025-26,AMF
940,C. Wright,Wigan Athletic,Wigan Athletic,"AMF, LCMF",25.0,700000,30/06/2026,37,3149,0.623966,...,NaN,NaN,-0.599203,-0.542246,-0.399827,-0.619779,-0.287286,-0.327661,England League One 2025-26,AMF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,"AMF, RW, DMF",25.0,0,30/06/2026,13,497,-1.134989,...,NaN,NaN,3.114491,1.301174,-0.399827,2.081851,-0.287286,-0.327661,England League Two 2025-26,AMF
19881,L. Cirino,Gillingham,Gillingham,"LAMF, LWB, LB",23.0,0,30/06/2026,12,492,-0.783198,...,NaN,NaN,-0.599203,-0.542246,-0.399827,0.284440,-0.287286,-0.327661,England League Two 2025-26,LAMF
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,"RAMF, RW",26.0,325000,30/06/2027,12,482,-1.134989,...,NaN,NaN,-0.166319,1.403586,-0.399827,-0.719022,-0.287286,-0.327661,England League Two 2025-26,RAMF
19890,C. Deeming,Cheltenham Town,Cheltenham Town,"RW, AMF, LCMF",19.0,0,30/06/2027,14,460,-1.134989,...,NaN,NaN,0.745017,1.505998,-0.399827,1.651795,-0.287286,-0.327661,England League Two 2025-26,RW
19891,E. Sutton,Harrogate Town,Harrogate Town,"LAMF, LW, RWB",19.0,0,31/05/2026,8,456,-0.783198,...,NaN,NaN,-0.599203,-0.542246,-0.399827,-0.719022,-0.287286,-0.327661,England League Two 2025-26,LAMF

In [7]:
# Function to normalize the data to a [0, 1] range
def NormalizeData(data):
    # Subtract the minimum value from each element and divide by the range
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Iterate over the specified columns (columns_to_zscore) to normalize them
for column in columns_to_zscore:
    # Apply the NormalizeData function to scale the column values
    z_score_df[column] = NormalizeData(z_score_df[column])

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,"RW, RAMF, RWB",28.0,300000,30/06/2027,39,3593,0.666667,...,NaN,NaN,0.411255,0.121212,0.0,0.337209,1.0,1.0,England League One 2025-26,RW
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,"RAMF, CF, LAMF",29.0,500000,NaN,40,3511,0.833333,...,NaN,NaN,0.000000,0.000000,0.0,0.000000,0.0,0.0,England League One 2025-26,RAMF
931,J. Diamond,Stockport County,Stockport County,"AMF, RWB",26.0,350000,30/06/2027,40,3215,0.500000,...,NaN,NaN,0.012987,0.000000,0.0,0.039535,0.0,0.0,England League One 2025-26,AMF
932,M. Harness,Huddersfield Town,Huddersfield Town,"AMF, RAMF, RCMF",30.0,800000,30/06/2028,40,3207,0.416667,...,NaN,NaN,0.086580,0.000000,0.0,0.234884,0.0,0.0,England League One 2025-26,AMF
940,C. Wright,Wigan Athletic,Wigan Athletic,"AMF, LCMF",25.0,700000,30/06/2026,37,3149,0.416667,...,NaN,NaN,0.000000,0.000000,0.0,0.020930,0.0,0.0,England League One 2025-26,AMF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,"AMF, RW, DMF",25.0,0,30/06/2026,13,497,0.000000,...,NaN,NaN,0.705628,0.272727,0.0,0.590698,0.0,0.0,England League Two 2025-26,AMF
19881,L. Cirino,Gillingham,Gillingham,"LAMF, LWB, LB",23.0,0,30/06/2026,12,492,0.083333,...,NaN,NaN,0.000000,0.000000,0.0,0.211628,0.0,0.0,England League Two 2025-26,LAMF
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,"RAMF, RW",26.0,325000,30/06/2027,12,482,0.000000,...,NaN,NaN,0.082251,0.287879,0.0,0.000000,0.0,0.0,England League Two 2025-26,RAMF
19890,C. Deeming,Cheltenham Town,Cheltenham Town,"RW, AMF, LCMF",19.0,0,30/06/2027,14,460,0.000000,...,NaN,NaN,0.255411,0.303030,0.0,0.500000,0.0,0.0,England League Two 2025-26,RW
19891,E. Sutton,Harrogate Town,Harrogate Town,"LAMF, LW, RWB",19.0,0,31/05/2026,8,456,0.083333,...,NaN,NaN,0.000000,0.000000,0.0,0.000000,0.0,0.0,England League Two 2025-26,LAMF

### Attribute Definition and Calculation

In [8]:
# Create new rating columns in a batch
new_columns = {
    
    # Template line: 'REPLACE Rating': z_score_df['REPLACE'] * 0,

    # Passing
    'Progressive passes per 90 Rating':     z_score_df['Progressive passes per 90']         * 0.20,
    'Accurate progressive passes % Rating': z_score_df['Accurate progressive passes, %']    * 0.20,
    'Passes per 90 Rating':                 z_score_df['Passes per 90']                     * 0.30,
    'Accurate passes % Rating':             z_score_df['Accurate passes, %']                * 0.30,

    # Creativity
    'Key passes per 90 Rating':         z_score_df['Key passes per 90']         * 0.40,
    'xA per 90 Rating':                 z_score_df['xA per 90']                 * 0.30,
    'Deep completions per 90 Rating':   z_score_df['Deep completions per 90']   * 0.30,

    # Crossing
    'Accurate crosses % Rating':    z_score_df['Accurate crosses, %']   * 0.60,
    'Crosses per 90 Rating':        z_score_df['Crosses per 90']        * 0.40,

    # Dribbling
    'Successful dribbles % Rating': z_score_df['Successful dribbles, %']    * 0.50,
    'Dribbles per 90 Rating':       z_score_df['Dribbles per 90']           * 0.35,
    'Accelerations per 90 Rating':  z_score_df['Accelerations per 90']      * 0.15,

    # Shooting
    'Non-penalty goals per 90 Rating':  z_score_df['Non-penalty goals per 90']  * 0.40,
    'xG per 90 Rating':                 z_score_df['xG per 90']                 * 0.30,
    'Shots on target % Rating':         z_score_df['Shots on target, %']        * 0.30,

    # Defending (Pressing)
    'Defensive duels won % Rating':                 z_score_df['Defensive duels won, %']                * 0.40,
    'Successful defensive actions per 90 Rating':   z_score_df['Successful defensive actions per 90']   * 0.30,
    'Defensive duels per 90 Rating':                z_score_df['Defensive duels per 90']                * 0.30
    
}

# Create the new attribute columns using the above ratings columns
# Template line: new_columns['REPLACE Att'] = new_columns['REPLACE'] + new_columns['REPLACE'] + new_columns['REPLACE'] + new_columns['REPLACE']
new_columns['Passing Att']      = new_columns['Progressive passes per 90 Rating'] + new_columns['Accurate progressive passes % Rating'] + new_columns['Passes per 90 Rating'] + new_columns['Accurate passes % Rating']
new_columns['Creativity Att']   = new_columns['Key passes per 90 Rating'] + new_columns['xA per 90 Rating'] + new_columns['Deep completions per 90 Rating']
new_columns['Crossing Att']     = new_columns['Accurate crosses % Rating'] + new_columns['Crosses per 90 Rating']
new_columns['Dribbling Att']    = new_columns['Successful dribbles % Rating'] + new_columns['Dribbles per 90 Rating'] + new_columns['Accelerations per 90 Rating']
new_columns['Shooting Att']     = new_columns['Non-penalty goals per 90 Rating'] + new_columns['xG per 90 Rating'] + new_columns['Shots on target % Rating']
new_columns['Defending Att']    = new_columns['Defensive duels won % Rating'] + new_columns['Successful defensive actions per 90 Rating'] + new_columns['Defensive duels per 90 Rating']

# Add all new columns to the DataFrame at once
z_score_df = pd.concat([z_score_df, pd.DataFrame(new_columns)], axis=1)

# Create a fresh copy of the df to avoid issues if re-running cells
z_score_df = z_score_df.copy()
z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Shots on target % Rating,Defensive duels won % Rating,Successful defensive actions per 90 Rating,Defensive duels per 90 Rating,Passing Att,Creativity Att,Crossing Att,Dribbling Att,Shooting Att,Defending Att
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,"RW, RAMF, RWB",28.0,300000,30/06/2027,39,3593,0.666667,...,0.135643,0.211097,0.101432,0.086766,0.498916,0.574778,0.464659,0.600687,0.395847,0.399295
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,"RAMF, CF, LAMF",29.0,500000,NaN,40,3511,0.833333,...,0.227700,0.155762,0.081608,0.098933,0.364890,0.310085,0.346451,0.447913,0.604231,0.336303
931,J. Diamond,Stockport County,Stockport County,"AMF, RWB",26.0,350000,30/06/2027,40,3215,0.500000,...,0.144729,0.263620,0.088216,0.092850,0.452150,0.398336,0.415183,0.574657,0.390647,0.444686
932,M. Harness,Huddersfield Town,Huddersfield Town,"AMF, RAMF, RCMF",30.0,800000,30/06/2028,40,3207,0.416667,...,0.177000,0.222144,0.174780,0.149840,0.591874,0.431765,0.354424,0.479218,0.398429,0.546764
940,C. Wright,Wigan Athletic,Wigan Athletic,"AMF, LCMF",25.0,700000,30/06/2026,37,3149,0.416667,...,0.181329,0.155059,0.153634,0.139594,0.551652,0.255296,0.352390,0.406730,0.417043,0.448288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,"AMF, RW, DMF",25.0,0,30/06/2026,13,497,0.000000,...,0.142843,0.168014,0.184361,0.121665,0.375594,0.224810,0.423900,0.269609,0.207129,0.474040
19881,L. Cirino,Gillingham,Gillingham,"LAMF, LWB, LB",23.0,0,30/06/2026,12,492,0.083333,...,0.142843,0.203866,0.223348,0.205229,0.206334,0.178095,0.439940,0.438389,0.389782,0.632444
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,"RAMF, RW",26.0,325000,30/06/2027,12,482,0.000000,...,0.085714,0.014060,0.043943,0.162647,0.457157,0.327966,0.184747,0.394747,0.228571,0.220649
19890,C. Deeming,Cheltenham Town,Cheltenham Town,"RW, AMF, LCMF",19.0,0,30/06/2027,14,460,0.000000,...,0.085714,0.260608,0.243172,0.228602,0.454632,0.221587,0.371461,0.424562,0.107143,0.732381
19891,E. Sutton,Harrogate Town,Harrogate Town,"LAMF, LW, RWB",19.0,0,31/05/2026,8,456,0.083333,...,0.214286,0.333015,0.148018,0.148879,0.452959,0.371304,0.417823,0.500606,0.463265,0.629912

In [9]:
# Create new df containing absolute values to append onto final ratings df later
absolute_columns = [# For join
                    'Player',
                    'Team within selected timeframe',
                    
                    # Passing
                    'Progressive passes per 90',
                    'Accurate progressive passes, %',
                    'Passes per 90',
                    'Accurate passes, %',

                    # Creativity
                    'Key passes per 90',
                    'xA per 90',
                    'Deep completions per 90',

                    # Crossing
                    'Accurate crosses, %',
                    'Crosses per 90',

                    # Dribbling
                    'Successful dribbles, %',
                    'Dribbles per 90',
                    'Accelerations per 90',

                    # Shooting
                    'Non-penalty goals per 90',
                    'xG per 90',
                    'Shots on target, %',

                    # Defending
                    'Defensive duels won, %',
                    'Successful defensive actions per 90',
                    'Defensive duels per 90',

                    # Aerial
                    'Aerial duels won, %',
                    'Aerial duels per 90',

                    # Set Pieces
                    'Free kicks per 90',
                    'Direct free kicks per 90',
                    'Direct free kicks on target, %',
                    'Corners per 90',
                    
                    ]
absolute_values = filtered_df[absolute_columns].copy()

absolute_values

,Player,Team within selected timeframe,Progressive passes per 90,"Accurate progressive passes, %",Passes per 90,"Accurate passes, %",Key passes per 90,xA per 90,Deep completions per 90,"Accurate crosses, %",...,"Shots on target, %","Defensive duels won, %",Successful defensive actions per 90,Defensive duels per 90,"Aerial duels won, %",Aerial duels per 90,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90
904,L. Molyneux,Doncaster Rovers,4.43,72.88,24.90,67.10,0.75,0.21,0.78,30.82,...,31.65,57.86,4.91,3.98,25.20,3.18,0.95,0.08,0.0,1.45
909,F. Onyedinma,Wycombe Wanderers,1.67,56.92,17.87,74.75,0.46,0.10,0.36,32.86,...,53.13,52.35,4.31,4.36,41.73,7.13,0.00,0.00,0.0,0.00
931,J. Diamond,Stockport County,2.74,60.20,23.01,73.84,0.56,0.13,0.53,35.11,...,33.77,63.09,4.51,4.17,42.42,1.85,0.03,0.00,0.0,0.17
932,M. Harness,Huddersfield Town,4.74,63.91,30.36,72.92,0.56,0.12,0.81,28.74,...,41.30,58.96,7.13,5.95,37.21,3.62,0.20,0.00,0.0,1.01
940,C. Wright,Wigan Athletic,3.74,65.65,26.24,75.93,0.26,0.07,0.66,35.85,...,42.31,52.28,6.49,5.63,41.51,4.54,0.00,0.00,0.0,0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,4.53,44.00,26.98,60.40,0.18,0.09,0.54,38.46,...,33.33,53.57,7.42,5.07,23.81,3.80,1.63,0.18,0.0,2.54
19881,L. Cirino,Gillingham,3.66,45.00,19.21,53.33,0.18,0.13,0.00,31.58,...,33.33,57.14,8.60,7.68,57.14,3.84,0.00,0.00,0.0,0.91
19882,J. Lankester,Crewe Alexandra,4.67,68.00,23.15,65.32,0.37,0.06,0.93,8.33,...,20.00,38.24,3.17,6.35,16.67,2.24,0.19,0.19,0.0,0.00
19890,C. Deeming,Cheltenham Town,4.11,57.14,24.85,68.50,0.39,0.09,0.00,28.57,...,20.00,62.79,9.20,8.41,28.57,4.11,0.59,0.20,0.0,2.15
19891,E. Sutton,Harrogate Town,5.53,75.00,20.92,62.26,0.59,0.04,0.79,31.25,...,50.00,70.00,6.32,5.92,28.57,1.38,0.00,0.00,0.0,0.00

In [10]:
# Creating the new DataFrame 'ratings' with the specified columns
ratings_columns = [
                    "Player", "Team", "Team within selected timeframe", "Main Position", "Position", "League",
                    "Age", "Market value", "Contract expires", "On loan", "Minutes played",
                    
                    # New Att columns created earlier:
                    "Passing Att", "Creativity Att", "Crossing Att", "Dribbling Att", "Shooting Att", "Defending Att"
                    ]

ratings = z_score_df[ratings_columns].copy()

ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Passing Att,Creativity Att,Crossing Att,Dribbling Att,Shooting Att,Defending Att
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,RW,"RW, RAMF, RWB",England League One 2025-26,28.0,300000,30/06/2027,no,3593,0.498916,0.574778,0.464659,0.600687,0.395847,0.399295
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,RAMF,"RAMF, CF, LAMF",England League One 2025-26,29.0,500000,NaN,no,3511,0.364890,0.310085,0.346451,0.447913,0.604231,0.336303
931,J. Diamond,Stockport County,Stockport County,AMF,"AMF, RWB",England League One 2025-26,26.0,350000,30/06/2027,no,3215,0.452150,0.398336,0.415183,0.574657,0.390647,0.444686
932,M. Harness,Huddersfield Town,Huddersfield Town,AMF,"AMF, RAMF, RCMF",England League One 2025-26,30.0,800000,30/06/2028,no,3207,0.591874,0.431765,0.354424,0.479218,0.398429,0.546764
940,C. Wright,Wigan Athletic,Wigan Athletic,AMF,"AMF, LCMF",England League One 2025-26,25.0,700000,30/06/2026,yes,3149,0.551652,0.255296,0.352390,0.406730,0.417043,0.448288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,AMF,"AMF, RW, DMF",England League Two 2025-26,25.0,0,30/06/2026,no,497,0.375594,0.224810,0.423900,0.269609,0.207129,0.474040
19881,L. Cirino,Gillingham,Gillingham,LAMF,"LAMF, LWB, LB",England League Two 2025-26,23.0,0,30/06/2026,no,492,0.206334,0.178095,0.439940,0.438389,0.389782,0.632444
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,RAMF,"RAMF, RW",England League Two 2025-26,26.0,325000,30/06/2027,no,482,0.457157,0.327966,0.184747,0.394747,0.228571,0.220649
19890,C. Deeming,Cheltenham Town,Cheltenham Town,RW,"RW, AMF, LCMF",England League Two 2025-26,19.0,0,30/06/2027,yes,460,0.454632,0.221587,0.371461,0.424562,0.107143,0.732381
19891,E. Sutton,Harrogate Town,Harrogate Town,LAMF,"LAMF, LW, RWB",England League Two 2025-26,19.0,0,31/05/2026,yes,456,0.452959,0.371304,0.417823,0.500606,0.463265,0.629912

In [11]:
# Normalise the data again after we have created attributes

# Ensure a copy of the DataFrame to prevent unintended changes to the original data
norm_ratings = ratings.copy()

# Select columns that end with the word "Att"
columns_to_normalize = [col for col in norm_ratings.columns if col.endswith('Att')]

# Iterate over the selected columns and apply normalization
for column in columns_to_normalize:

    # Apply the NormalizeData function to scale the column
    norm_ratings[column] = NormalizeData(norm_ratings[column])

norm_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Passing Att,Creativity Att,Crossing Att,Dribbling Att,Shooting Att,Defending Att
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,RW,"RW, RAMF, RWB",England League One 2025-26,28.0,300000,30/06/2027,no,3593,0.514684,0.727533,0.690507,0.809426,0.486608,0.452100
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,RAMF,"RAMF, CF, LAMF",England League One 2025-26,29.0,500000,NaN,no,3511,0.340277,0.392494,0.514844,0.603564,0.742771,0.364373
931,J. Diamond,Stockport County,Stockport County,AMF,"AMF, RWB",England League One 2025-26,26.0,350000,30/06/2027,no,3215,0.453827,0.504199,0.616984,0.774351,0.480216,0.515313
932,M. Harness,Huddersfield Town,Huddersfield Town,AMF,"AMF, RAMF, RCMF",England League One 2025-26,30.0,800000,30/06/2028,no,3207,0.635649,0.546512,0.526693,0.645747,0.489782,0.657471
940,C. Wright,Wigan Athletic,Wigan Athletic,AMF,"AMF, LCMF",England League One 2025-26,25.0,700000,30/06/2026,yes,3149,0.583309,0.323145,0.523670,0.548069,0.512664,0.520329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,AMF,"AMF, RW, DMF",England League Two 2025-26,25.0,0,30/06/2026,no,497,0.354206,0.284556,0.629938,0.363299,0.254620,0.556193
19881,L. Cirino,Gillingham,Gillingham,LAMF,"LAMF, LWB, LB",England League Two 2025-26,23.0,0,30/06/2026,no,492,0.133948,0.225426,0.653775,0.590730,0.479152,0.776793
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,RAMF,"RAMF, RW",England League Two 2025-26,26.0,325000,30/06/2027,no,482,0.460344,0.415127,0.274544,0.531922,0.280979,0.203309
19890,C. Deeming,Cheltenham Town,Cheltenham Town,RW,"RW, AMF, LCMF",England League Two 2025-26,19.0,0,30/06/2027,yes,460,0.457057,0.280477,0.552011,0.572098,0.131709,0.915971
19891,E. Sutton,Harrogate Town,Harrogate Town,LAMF,"LAMF, LW, RWB",England League Two 2025-26,19.0,0,31/05/2026,yes,456,0.454880,0.469983,0.620907,0.674567,0.569485,0.773268

### Weighting the Attributes to Create an Overall Rating

In [12]:
# Weight the overall attributes in terms of importance 
weighted_ratings = norm_ratings.copy()

#Weight the overall ratings
weighted_ratings['Passing Att'] =       weighted_ratings['Passing Att']     * 0.30
weighted_ratings['Creativity Att'] =    weighted_ratings['Creativity Att']  * 0.20
weighted_ratings['Crossing Att'] =      weighted_ratings['Crossing Att']    * 0.10
weighted_ratings['Dribbling Att'] =     weighted_ratings['Dribbling Att']   * 0.15
weighted_ratings['Shooting Att'] =      weighted_ratings['Shooting Att']    * 0.10
weighted_ratings['Defending Att'] =     weighted_ratings['Defending Att']   * 0.15


weighted_ratings['Winger Rating'] = ( weighted_ratings['Passing Att'] 
                                    + weighted_ratings['Creativity Att'] 
                                    + weighted_ratings['Crossing Att'] 
                                    + weighted_ratings['Dribbling Att'] 
                                    + weighted_ratings['Shooting Att'] 
                                    + weighted_ratings['Defending Att']
                                    )

weighted_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Passing Att,Creativity Att,Crossing Att,Dribbling Att,Shooting Att,Defending Att,Winger Rating
904,L. Molyneux,Doncaster Rovers,Doncaster Rovers,RW,"RW, RAMF, RWB",England League One 2025-26,28.0,300000,30/06/2027,no,3593,0.154405,0.145507,0.069051,0.121414,0.048661,0.067815,0.606852
909,F. Onyedinma,Wycombe Wanderers,Wycombe Wanderers,RAMF,"RAMF, CF, LAMF",England League One 2025-26,29.0,500000,NaN,no,3511,0.102083,0.078499,0.051484,0.090535,0.074277,0.054656,0.451534
931,J. Diamond,Stockport County,Stockport County,AMF,"AMF, RWB",England League One 2025-26,26.0,350000,30/06/2027,no,3215,0.136148,0.100840,0.061698,0.116153,0.048022,0.077297,0.540158
932,M. Harness,Huddersfield Town,Huddersfield Town,AMF,"AMF, RAMF, RCMF",England League One 2025-26,30.0,800000,30/06/2028,no,3207,0.190695,0.109302,0.052669,0.096862,0.048978,0.098621,0.597127
940,C. Wright,Wigan Athletic,Wigan Athletic,AMF,"AMF, LCMF",England League One 2025-26,25.0,700000,30/06/2026,yes,3149,0.174993,0.064629,0.052367,0.082210,0.051266,0.078049,0.503515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19879,S. Solomon,Tranmere Rovers,Tranmere Rovers,AMF,"AMF, RW, DMF",England League Two 2025-26,25.0,0,30/06/2026,no,497,0.106262,0.056911,0.062994,0.054495,0.025462,0.083429,0.389552
19881,L. Cirino,Gillingham,Gillingham,LAMF,"LAMF, LWB, LB",England League Two 2025-26,23.0,0,30/06/2026,no,492,0.040184,0.045085,0.065377,0.088609,0.047915,0.116519,0.403691
19882,J. Lankester,Crewe Alexandra,Crewe Alexandra,RAMF,"RAMF, RW",England League Two 2025-26,26.0,325000,30/06/2027,no,482,0.138103,0.083025,0.027454,0.079788,0.028098,0.030496,0.386965
19890,C. Deeming,Cheltenham Town,Cheltenham Town,RW,"RW, AMF, LCMF",England League Two 2025-26,19.0,0,30/06/2027,yes,460,0.137117,0.056095,0.055201,0.085815,0.013171,0.137396,0.484795
19891,E. Sutton,Harrogate Town,Harrogate Town,LAMF,"LAMF, LW, RWB",England League Two 2025-26,19.0,0,31/05/2026,yes,456,0.136464,0.093997,0.062091,0.101185,0.056948,0.115990,0.566675

In [13]:
# Final time to normalise, this time for the overall rating 

# Ensure a copy of the DataFrame to prevent unintended changes
final_ratings = weighted_ratings.copy()

# Select the attribute and rating columns in the DataFrame
columns_to_normalize = [col for col in final_ratings.columns if col.endswith('Att') or col.endswith('Rating')]

# Normalise the attribute and rating columns
for column in columns_to_normalize:
    final_ratings[column] = NormalizeData(final_ratings[column]) # function defined earlier

# Multiply columns ending with 'Att' or 'Rating' by 100 and round to 2 decimal places
final_ratings[columns_to_normalize] = (final_ratings[columns_to_normalize] * 100).round(2)

# Sort the DataFrame by the last column in descending order
rating_column = [col for col in final_ratings.columns if col.endswith('Rating')]
final_ratings.sort_values(by=rating_column, ascending=False, inplace=True)

# Merge the absolute values
final_ratings = final_ratings.merge(absolute_values,on=['Player','Team within selected timeframe'], how='left')

# Reset the index of the sorted DataFrame to ensure a clean, sequential index
final_ratings.reset_index(drop=True, inplace=True)

# Export the ratings to CSV
final_ratings.to_csv(rating_export_name, index=False)
print(f"Ratings exported at {datetime.now().strftime('%d-%m-%Y %H:%M')}")

final_ratings

Ratings exported at 18-05-2026 16:36

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,...,"Shots on target, %","Defensive duels won, %",Successful defensive actions per 90,Defensive duels per 90,"Aerial duels won, %",Aerial duels per 90,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90
0,C. Willock,Cardiff City,Cardiff City,LAMF,"LAMF, LW",England League One 2025-26,28.0,1800000,30/06/2027,no,...,34.09,70.00,3.86,3.41,11.54,0.98,0.00,0.00,0.00,1.36
1,A. Cozier-Duberry,Bolton Wanderers,Bolton Wanderers,RAMF,RAMF,England League One 2025-26,20.0,0,30/06/2028,yes,...,32.47,63.78,4.95,4.52,12.50,0.57,0.04,0.04,0.00,0.04
2,R. Colwill,Cardiff City,Cardiff City,AMF,"AMF, CF, RCMF",England League One 2025-26,23.0,1200000,30/06/2030,no,...,36.51,60.00,4.82,4.05,45.59,2.75,0.36,0.32,37.50,0.12
3,C. Vernam,Grimsby Town,Grimsby Town,LW,LW,England League Two 2025-26,29.0,150000,30/06/2027,no,...,45.57,62.03,3.73,2.56,36.59,2.66,0.94,0.19,16.67,3.44
4,O. Tanner,Cardiff City,Cardiff City,RAMF,"RAMF, RWF, RW",England League One 2025-26,23.0,1500000,30/06/2029,no,...,25.00,60.98,4.95,4.14,46.15,1.97,0.25,0.00,0.00,2.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,P. Lane,Reading,Reading,LAMF,"LAMF, RWF, LW",England League One 2025-26,25.0,0,30/06/2028,no,...,32.00,53.03,4.42,3.27,25.76,3.27,0.00,0.00,0.00,0.05
186,D. Watmore,Rotherham United,Rotherham United,AMF,"AMF, CF, LAMF",England League One 2025-26,32.0,900000,30/06/2026,no,...,0.00,55.56,1.84,1.27,18.18,3.11,0.00,0.00,0.00,0.00
187,R. Sotiriou,Hapoel Jerusalem,Bristol Rovers,AMF,"AMF, CF, LW",England League Two 2025-26,25.0,500000,30/06/2028,no,...,30.00,66.67,3.78,3.29,32.35,4.14,0.00,0.00,0.00,0.00
188,H. Bettoni,Wigan Athletic,Wigan Athletic,AMF,"AMF, CF",England League One 2025-26,18.0,0,NaN,no,...,35.71,50.00,2.32,2.20,28.57,3.41,1.46,0.24,100.00,1.83
189,W. Keane,Reading,Reading,AMF,"AMF, CF, RCMF",England League One 2025-26,33.0,900000,30/06/2026,yes,...,40.00,50.00,3.43,3.43,28.00,7.79,0.00,0.00,0.00,0.00