# Player Attribute Ratings System

### Setup and Inputs

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
from datetime import datetime

In [2]:
# Load the latest Wyscout dataset available

df = pd.read_csv("Wyscout_League_Export 2026-04-14.csv")

In [3]:
# Create list of unique leagues within dataset

list_unique_leagues = list( sorted( df['League'].unique() ) )
list_unique_leagues

['Albania Superiore League 2024-25',
 'Albania Superiore League 2025-26',
 'Argentina Primera Division 2025',
 'Argentina Primera Division 2026',
 'Australia A-League 2024-25',
 'Australia A-League 2025-26',
 'Austria Bundesliga 2024-25',
 'Austria Bundesliga 2025-26',
 'Belgium First Division A 2024-25',
 'Belgium First Division A 2025-26',
 'Belgium First Division B 2024-25',
 'Belgium First Division B 2025-26',
 'Bolivia Primera Division 2025',
 'Bosnia Premijer Liga 2024-25',
 'Bosnia Premijer Liga 2025-26',
 'Brazil Serie A 2025',
 'Brazil Serie A 2026',
 'Brazil Serie B 2025',
 'Brazil Serie B 2026',
 'Bulgaria First League 2024-25',
 'Bulgaria First League 2025-26',
 'Canada Premier League 2025',
 'Chile Primera Division 2025',
 'Chile Primera Division 2026',
 'China Super League 2025',
 'China Super League 2026',
 'Colombia Primera A 2025',
 'Colombia Primera A 2026',
 'Costa Rica Primera Division 2024-25',
 'Costa Rica Primera Division 2025-26',
 'Croatia 1.HNL 2024-25',
 'Croatia 1.HNL 2025-26',
 'Cyprus First Division 2024-25',
 'Cyprus First Division 2025-26',
 'Czech Fortuna Liga 2024-25',
 'Czech Fortuna Liga 2025-26',
 'Denmark 1st Division 2024-25',
 'Denmark 1st Division 2025-26',
 'Denmark Superliga 2024-25',
 'Denmark Superliga 2025-26',
 'Ecuador Serie A 2025',
 'Ecuador Serie A 2026',
 'Egypt Premier League 2024-25',
 'Egypt Premier League 2025-26',
 'England Championship 2024-25',
 'England Championship 2025-26',
 'England League One 2024-25',
 'England League One 2025-26',
 'England League Two 2024-25',
 'England League Two 2025-26',
 'England National League 2024-25',
 'England National League 2025-26',
 'England National League North South 2024-25',
 'England National League North South 2025-26',
 'England Premier League 2024-25',
 'England Premier League 2025-26',
 'Estonia Meistriliiga 2025',
 'Estonia Meistriliiga 2026',
 'Finland Veikkausliiga 2025',
 'France Championnat National 2024-25',
 'France Championnat National 2025-26',
 'France Ligue 1 2024-25',
 'France Ligue 1 2025-26',
 'France Ligue 2 2024-25',
 'France Ligue 2 2025-26',
 'Georgia Erovnuli Liga 2025',
 'Georgia Erovnuli Liga 2026',
 'Germany 2. Bundesliga 2024-25',
 'Germany 2. Bundesliga 2025-26',
 'Germany 3. Liga 2024-25',
 'Germany 3. Liga 2025-26',
 'Germany Bundesliga 2024-25',
 'Germany Bundesliga 2025-26',
 'Greece Super League 2024-25',
 'Greece Super League 2025-26',
 'Hungary NB1 2024-25',
 'Hungary NB1 2025-26',
 'Indonesia Liga 1 2024-25',
 'Indonesia Liga 1 2025-26',
 'Ireland First Division 2025',
 'Ireland First Division 2026',
 'Ireland Premier Division 2025',
 'Ireland Premier Division 2026',
 "Israel Ligat Ha'Al 2024-25",
 "Israel Ligat Ha'Al 2025-26",
 'Italy Campionato Primavera 1 2024-25',
 'Italy Campionato Primavera 1 2025-26',
 'Italy Serie A 2024-25',
 'Italy Serie A 2025-26',
 'Italy Serie B 2024-25',
 'Italy Serie B 2025-26',
 'Japan J1 100 Year Vision League 2026',
 'Japan J1-League 2025',
 'Japan J2-J3 100 Year Vision League 2026',
 'Japan J2-League 2025',
 'Kazakhstan Premier League 2025',
 'Kazakhstan Premier League 2026',
 'Korea K-League 1 2025',
 'Korea K-League 1 2026',
 'Korea K-League 2 2025',
 'Korea K-League 2 2026',
 'Latvia Virsliga 2025',
 'Latvia Virsliga 2026',
 'Malaysia Super League 2024-25',
 'Malaysia Super League 2025-26',
 'Mexico Liga MX 2024-25',
 'Mexico Liga MX 2025-26',
 'Mexico Liga de Expansion 2024-25',
 'Mexico Liga de Expansion 2025-26',
 'Morocco Botola Pro 2024-25',
 'Morocco Botola Pro 2025-26',
 'Netherlands Eerste Divisie 2024-25',
 'Netherlands Eerste Divisie 2025-26',
 'Netherlands Eredivisie 2024-25',
 'Netherlands Eredivisie 2025-26',
 'Northern Ireland Premiership 2024-25',
 'Northern Ireland Premiership 2025-26',
 'Norway Eliteserien 2025',
 'Norway Eliteserien 2026',
 'Norway First Division 2025',
 'Paraguay Primera Division 2025',
 'Paraguay Primera Division 2026',
 'Peru Primera Division 2025',
 'Peru Primera Division 2026',
 'Poland 1 Liga 2024-25',
 'Poland 1 Liga 2025-26',
 'Poland Ekstraklasa 2024-25',
 'Poland Ekstraklasa 2025-26',
 'Portugal Primeira Liga 2024-25',
 'Portugal Primeira Liga 2025-26',
 'Portugal Segunda Liga 2024-25',
 'Portugal Segunda Liga 2025-26',
 'Romania SuperLiga 2024-25',
 'Romania SuperLiga 2025-26',
 'Russia Premier League 2024-25',
 'Russia Premier League 2025-26',
 'Scotland Championship 2024-25',
 'Scotland Championship 2025-26',
 'Scotland League One 2024-25',
 'Scotland League One 2025-26',
 'Scotland League Two 2024-25',
 'Scotland League Two 2025-26',
 'Scotland Premiership 2024-25',
 'Scotland Premiership 2025-26',
 'Serbia Prva Liga 2025-26',
 'Serbia Super Liga 2024-25',
 'Serbia Super Liga 2025-26',
 'Slovakia Super Liga 2024-25',
 'Slovakia Super Liga 2025-26',
 'Slovenia Prva Liga 2024-25',
 'Slovenia Prva Liga 2025-26',
 'South Africa PSL 2024-25',
 'South Africa PSL 2025-26',
 'Spain La Liga 2024-25',
 'Spain La Liga 2025-26',
 'Spain Primera Division RFEF 2024-25',
 'Spain Primera Division RFEF 2025-26',
 'Spain Segunda 2024-25',
 'Spain Segunda 2025-26',
 'Sweden Allsvenskan 2025',
 'Switzerland Challenge League 2024-25',
 'Switzerland Challenge League 2025-26',
 'Switzerland Super League 2024-25',
 'Switzerland Super League 2025-26',
 'Turkey Super Lig 2024-25',
 'Turkey Super Lig 2025-26',
 'USA MLS 2025',
 'USA MLS 2026',
 'USA MLS Next Pro 2025',
 'USA MLS Next Pro 2026',
 'USA USL Championship 2025',
 'USA USL Championship 2026',
 'USA USL League 1 2025',
 'USA USL League 1 2026',
 'Ukraine Premier League 2024-25',
 'Ukraine Premier League 2025-26',
 'Uruguay Primera Division 2025',
 'Uruguay Primera Division 2026',
 'Uzbekistan Super League 2025',
 'Uzbekistan Super League 2026',
 'Venezuela Primera Division 2025',
 'Venezuela Primera Division 2026']

In [4]:
# Filter settings used later in code

filter_positions = ["GK"]
filter_leagues = [#'England Championship 2025-26',
                  'England League One 2025-26',
                  'England League Two 2025-26']
filter_minutes = 450

# Columns to exclude from the Z-Score Calculation
excluded_columns = ['Player', 'Team', 'Team within selected timeframe', 'Position','Age', 'Market value', 'Contract expires', 'Matches played', 'Minutes played','Birth country', 'Passport country', 'Foot', 'Height', 'Weight', 'On loan','League', 'Main Position']

# Export names
rating_export_name = "CUFC Ratings - GK.csv"

### Calculate Z-Scores and Export Data for Review

In [5]:
# Create filtered df prior to applying the filters
filtered_df = df.copy()

# Apply filters to the filtered df
filtered_df = filtered_df[ filtered_df['League'].isin(filter_leagues) ]             # filter leagues
filtered_df = filtered_df[ filtered_df['Main Position'].isin(filter_positions) ]    # filter position
filtered_df = filtered_df[ filtered_df['Minutes played'] >= filter_minutes ]        # filter minutes played

filtered_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,24.0,800000,30/06/2028,42,4143,0,...,1.80,0.22,NaN,NaN,NaN,0.0,0,0.0,England League One 2025-26,GK
870,G. Wickens,Lincoln City,Lincoln City,GK,24.0,150000,30/06/2028,41,4087,0,...,1.56,0.40,NaN,NaN,NaN,0.0,0,0.0,England League One 2025-26,GK
871,S. Walker,Bradford City,Bradford City,GK,34.0,125000,30/06/2027,41,4086,0,...,1.48,0.29,NaN,NaN,NaN,0.0,0,0.0,England League One 2025-26,GK
875,Joel Pereira,Reading,Reading,GK,29.0,250000,30/06/2028,40,4022,0,...,1.83,0.40,NaN,NaN,NaN,0.0,0,0.0,England League One 2025-26,GK
884,J. Keeley,Luton Town,Luton Town,GK,22.0,200000,30/06/2027,39,3919,0,...,1.22,0.51,NaN,NaN,NaN,0.0,0,0.0,England League One 2025-26,GK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,29.0,100000,30/06/2026,11,1093,0,...,1.32,0.25,NaN,NaN,NaN,0.0,0,0.0,England League Two 2025-26,GK
19778,J. Wollacott,Crawley Town,Crawley Town,GK,29.0,300000,30/06/2026,9,910,0,...,1.38,0.20,NaN,NaN,NaN,0.0,0,0.0,England League Two 2025-26,GK
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,20.0,0,31/05/2026,6,596,0,...,0.91,0.45,NaN,NaN,NaN,0.0,0,0.0,England League Two 2025-26,GK
19866,S. Waller,Harrogate Town,Harrogate Town,GK,22.0,0,30/06/2026,6,528,0,...,1.36,0.34,NaN,NaN,NaN,0.0,0,0.0,England League Two 2025-26,GK
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,30.0,200000,30/06/2027,5,499,0,...,1.44,0.36,NaN,NaN,NaN,0.0,0,0.0,England League Two 2025-26,GK

In [6]:
# Calculate the z-scores for all metric columns

z_score_df = filtered_df.copy() # create a new df that is a copy of the filtered df

columns_to_zscore = [col for col in filtered_df.columns if col not in excluded_columns] # creates a list of all columns that are not in the excluded list, i.e. a list of columns to convert into z-scores

z_score_df[columns_to_zscore] = z_score_df[columns_to_zscore].apply(zscore) # takes the metric columns subset of the filtered_df, calculates the z-score for each data point and replaces the absolute value with the z-score

# the apply function works column-wise by default - i.e. for each column, calculate the z-score for each value in the column
# then it is assign back into the original filtered_df. This only works because the output (z-scores) are the same length as the input (filtered_df)

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,24.0,800000,30/06/2028,42,4143,NaN,...,0.546588,-1.022956,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
870,G. Wickens,Lincoln City,Lincoln City,GK,24.0,150000,30/06/2028,41,4087,NaN,...,-0.024745,-0.038846,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
871,S. Walker,Bradford City,Bradford City,GK,34.0,125000,30/06/2027,41,4086,NaN,...,-0.215190,-0.640247,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
875,Joel Pereira,Reading,Reading,GK,29.0,250000,30/06/2028,40,4022,NaN,...,0.618004,-0.038846,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
884,J. Keeley,Luton Town,Luton Town,GK,22.0,200000,30/06/2027,39,3919,NaN,...,-0.834134,0.562554,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,29.0,100000,30/06/2026,11,1093,NaN,...,-0.596078,-0.858938,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19778,J. Wollacott,Crawley Town,Crawley Town,GK,29.0,300000,30/06/2026,9,910,NaN,...,-0.453245,-1.132301,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,20.0,0,31/05/2026,6,596,NaN,...,-1.572105,0.234517,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19866,S. Waller,Harrogate Town,Harrogate Town,GK,22.0,0,30/06/2026,6,528,NaN,...,-0.500856,-0.366883,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,30.0,200000,30/06/2027,5,499,NaN,...,-0.310412,-0.257537,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK

In [7]:
# Function to normalize the data to a [0, 1] range
def NormalizeData(data):
    # Subtract the minimum value from each element and divide by the range
    return (data - np.min(data)) / (np.max(data) - np.min(data))

# Iterate over the specified columns (columns_to_zscore) to normalize them
for column in columns_to_zscore:
    # Apply the NormalizeData function to scale the column values
    z_score_df[column] = NormalizeData(z_score_df[column])

z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,Exits per 90,Aerial duels per 90.1,Free kicks per 90,Direct free kicks per 90,"Direct free kicks on target, %",Corners per 90,Penalties taken,"Penalty conversion, %",League,Main Position
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,24.0,800000,30/06/2028,42,4143,NaN,...,0.532751,0.217822,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
870,G. Wickens,Lincoln City,Lincoln City,GK,24.0,150000,30/06/2028,41,4087,NaN,...,0.427948,0.396040,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
871,S. Walker,Bradford City,Bradford City,GK,34.0,125000,30/06/2027,41,4086,NaN,...,0.393013,0.287129,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
875,Joel Pereira,Reading,Reading,GK,29.0,250000,30/06/2028,40,4022,NaN,...,0.545852,0.396040,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
884,J. Keeley,Luton Town,Luton Town,GK,22.0,200000,30/06/2027,39,3919,NaN,...,0.279476,0.504950,NaN,NaN,NaN,NaN,NaN,NaN,England League One 2025-26,GK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,29.0,100000,30/06/2026,11,1093,NaN,...,0.323144,0.247525,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19778,J. Wollacott,Crawley Town,Crawley Town,GK,29.0,300000,30/06/2026,9,910,NaN,...,0.349345,0.198020,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,20.0,0,31/05/2026,6,596,NaN,...,0.144105,0.445545,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19866,S. Waller,Harrogate Town,Harrogate Town,GK,22.0,0,30/06/2026,6,528,NaN,...,0.340611,0.336634,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,30.0,200000,30/06/2027,5,499,NaN,...,0.375546,0.356436,NaN,NaN,NaN,NaN,NaN,NaN,England League Two 2025-26,GK

### Attribute Definition and Calculation

In [8]:
# Create new rating columns in a batch
new_columns = {
    
    # Shot Stopping
    'Prevented Goals per 90 Rating':    z_score_df['Prevented goals per 90'] * 0.6,
    'Save % Rating':                    z_score_df['Save rate, %'] * 0.4,

    # Aerial
    'Aerial duels Won % Rating':    z_score_df['Aerial duels won, %'] * 0.7,
    'Aerial duels per 90 Rating':   z_score_df['Aerial duels per 90'] * 0.3,

    # Sweeping
    'Exits per 90 Rating':          z_score_df['Exits per 90'] * 0.5,
    'PAdj Interceptions Rating':    z_score_df['PAdj Interceptions'] * 0.5,

    # Short Distribution
    'Short Pass % Rating':          z_score_df['Accurate short / medium passes, %'] * 0.6,
    'Short Pass per 90 Rating':     z_score_df['Short / medium passes per 90'] * 0.4,
    #'Average Pass Length Rating':   z_score_df['Average pass length, m'] * 0.2,

    # Long Distribution
    'Long Pass % Rating':               z_score_df['Accurate long passes, %'] * 0.6,
    'Long Pass per 90 Rating':          z_score_df['Long passes per 90'] * 0.4,
    #'Average Long Pass Length Rating':  z_score_df['Average long pass length, m'] * 0.2,
}

# Create the new attribute columns using the above ratings columns
new_columns['Shot Stopping Att'] = new_columns['Prevented Goals per 90 Rating'] + new_columns['Save % Rating']
new_columns['Aerial Att'] = new_columns['Aerial duels Won % Rating'] + new_columns['Aerial duels per 90 Rating']
new_columns['Sweeping Att'] = new_columns['Exits per 90 Rating'] + new_columns['PAdj Interceptions Rating']
new_columns['Short Dist Att'] = new_columns['Short Pass % Rating'] + new_columns['Short Pass per 90 Rating'] #+ new_columns['Average Pass Length Rating']
new_columns['Long Dist Att'] = new_columns['Long Pass % Rating'] + new_columns['Long Pass per 90 Rating'] #+ new_columns['Average Long Pass Length Rating']

# Add all new columns to the DataFrame at once
z_score_df = pd.concat([z_score_df, pd.DataFrame(new_columns)], axis=1)

# Create a fresh copy of the df to avoid issues if re-running cells
z_score_df = z_score_df.copy()
z_score_df

,Player,Team,Team within selected timeframe,Position,Age,Market value,Contract expires,Matches played,Minutes played,Goals,...,PAdj Interceptions Rating,Short Pass % Rating,Short Pass per 90 Rating,Long Pass % Rating,Long Pass per 90 Rating,Shot Stopping Att,Aerial Att,Sweeping Att,Short Dist Att,Long Dist Att
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,24.0,800000,30/06/2028,42,4143,NaN,...,0.076835,0.499010,0.116375,0.255834,0.145196,0.690950,0.695347,0.343210,0.615385,0.401030
870,G. Wickens,Lincoln City,Lincoln City,GK,24.0,150000,30/06/2028,41,4087,NaN,...,0.040138,0.357756,0.091793,0.424864,0.351246,0.659999,0.624352,0.254111,0.449549,0.776109
871,S. Walker,Bradford City,Bradford City,GK,34.0,125000,30/06/2027,41,4086,NaN,...,0.058486,0.302310,0.052431,0.305562,0.100000,0.540203,0.732309,0.254993,0.354741,0.405562
875,Joel Pereira,Reading,Reading,GK,29.0,250000,30/06/2028,40,4022,NaN,...,0.077982,0.502310,0.267911,0.211778,0.178648,0.483787,0.741042,0.350907,0.770222,0.390425
884,J. Keeley,Luton Town,Luton Town,GK,22.0,200000,30/06/2027,39,3919,NaN,...,0.253440,0.498350,0.215947,0.252781,0.137011,0.499731,0.660595,0.393178,0.714297,0.389791
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,29.0,100000,30/06/2026,11,1093,NaN,...,0.224771,0.454125,0.135511,0.256489,0.148043,0.403465,0.774257,0.386343,0.589637,0.404531
19778,J. Wollacott,Crawley Town,Crawley Town,GK,29.0,300000,30/06/2026,9,910,NaN,...,0.285550,0.474587,0.284403,0.172083,0.069751,0.345810,0.759406,0.460223,0.758990,0.241834
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,20.0,0,31/05/2026,6,596,NaN,...,0.236239,0.000000,0.193855,0.321483,0.227758,0.201096,0.600353,0.308291,0.193855,0.549241
19866,S. Waller,Harrogate Town,Harrogate Town,GK,22.0,0,30/06/2026,6,528,NaN,...,0.045872,0.502970,0.141579,0.348528,0.028470,0.872144,0.800990,0.216177,0.644549,0.376998
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,30.0,200000,30/06/2027,5,499,NaN,...,0.176606,0.491749,0.132400,0.481570,0.269395,0.668139,0.806931,0.364378,0.624149,0.750965

In [9]:
# Create new df containing absolute values to append onto final ratings df later
absolute_columns = [# For join
                    'Player',
                    'Team within selected timeframe',

                    #Shot Stopping
                    'Prevented goals per 90',
                    'Save rate, %',
                    'Shots against per 90',
                    
                    # Aerial
                    'Aerial duels won, %',
                    'Aerial duels per 90',
                    
                    # Sweeping
                    'Exits per 90',
                    'PAdj Interceptions',

                    # Short Distribution
                    'Accurate short / medium passes, %',
                    'Short / medium passes per 90',
                    'Average pass length, m',

                    # Long Distribution
                    'Accurate long passes, %',
                    'Long passes per 90',
                    'Average long pass length, m']

absolute_values = filtered_df[absolute_columns].copy()

absolute_values

,Player,Team within selected timeframe,Prevented goals per 90,"Save rate, %",Shots against per 90,"Aerial duels won, %",Aerial duels per 90,Exits per 90,PAdj Interceptions,"Accurate short / medium passes, %",Short / medium passes per 90,"Average pass length, m","Accurate long passes, %",Long passes per 90,"Average long pass length, m"
869,S. Tickle,Wigan Athletic,0.098,68.02,3.74,90.00,0.22,1.80,1.63,98.47,9.97,39.51,58.79,11.12,54.68
870,G. Wickens,Lincoln City,-0.020,72.22,2.77,72.22,0.40,1.56,1.31,96.33,8.39,45.85,66.54,16.91,54.96
871,S. Walker,Bradford City,-0.091,68.53,3.15,92.31,0.29,1.48,1.47,95.49,5.86,44.55,61.07,9.85,55.02
875,Joel Pereira,Reading,-0.130,67.08,3.60,88.89,0.40,1.83,1.64,98.52,19.71,32.24,56.77,12.06,51.65
884,J. Keeley,Luton Town,-0.060,64.44,3.10,72.73,0.51,1.22,3.17,98.46,16.37,34.05,58.65,10.89,51.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Newport County,-0.110,61.11,4.45,100.00,0.25,1.32,2.92,97.79,11.20,37.52,58.82,11.20,52.28
19778,J. Wollacott,Crawley Town,-0.176,60.98,4.05,100.00,0.20,1.38,3.45,98.10,20.77,28.61,54.95,9.00,55.16
19848,E. Harrison,Shrewsbury Town,-0.423,64.86,5.59,66.67,0.45,0.91,3.02,90.91,14.95,37.42,61.80,13.44,49.44
19866,S. Waller,Harrogate Town,0.159,76.00,4.26,100.00,0.34,1.36,1.36,98.53,11.59,37.60,63.04,7.84,52.78
19877,L. McGee,Tranmere Rovers,0.097,66.67,2.16,100.00,0.36,1.44,2.50,98.36,11.00,43.52,69.14,14.61,56.04

In [10]:
# Creating the new DataFrame 'ratings' with the specified columns
ratings_columns = [
    "Player", "Team", "Team within selected timeframe", "Main Position", "Position", "League",
    "Age", "Market value", "Contract expires", "On loan", "Minutes played",
    "Shot Stopping Att", "Aerial Att", "Sweeping Att", "Short Dist Att", "Long Dist Att"]

ratings = z_score_df[ratings_columns].copy()

ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Shot Stopping Att,Aerial Att,Sweeping Att,Short Dist Att,Long Dist Att
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,GK,England League One 2025-26,24.0,800000,30/06/2028,no,4143,0.690950,0.695347,0.343210,0.615385,0.401030
870,G. Wickens,Lincoln City,Lincoln City,GK,GK,England League One 2025-26,24.0,150000,30/06/2028,no,4087,0.659999,0.624352,0.254111,0.449549,0.776109
871,S. Walker,Bradford City,Bradford City,GK,GK,England League One 2025-26,34.0,125000,30/06/2027,no,4086,0.540203,0.732309,0.254993,0.354741,0.405562
875,Joel Pereira,Reading,Reading,GK,GK,England League One 2025-26,29.0,250000,30/06/2028,no,4022,0.483787,0.741042,0.350907,0.770222,0.390425
884,J. Keeley,Luton Town,Luton Town,GK,GK,England League One 2025-26,22.0,200000,30/06/2027,no,3919,0.499731,0.660595,0.393178,0.714297,0.389791
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,GK,England League Two 2025-26,29.0,100000,30/06/2026,no,1093,0.403465,0.774257,0.386343,0.589637,0.404531
19778,J. Wollacott,Crawley Town,Crawley Town,GK,GK,England League Two 2025-26,29.0,300000,30/06/2026,no,910,0.345810,0.759406,0.460223,0.758990,0.241834
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,GK,England League Two 2025-26,20.0,0,31/05/2026,no,596,0.201096,0.600353,0.308291,0.193855,0.549241
19866,S. Waller,Harrogate Town,Harrogate Town,GK,GK,England League Two 2025-26,22.0,0,30/06/2026,no,528,0.872144,0.800990,0.216177,0.644549,0.376998
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,GK,England League Two 2025-26,30.0,200000,30/06/2027,no,499,0.668139,0.806931,0.364378,0.624149,0.750965

In [11]:
# Normalise the data again after we have created attributes

# Ensure a copy of the DataFrame to prevent unintended changes to the original data
norm_ratings = ratings.copy()

# Select columns that end with the word "Att"
columns_to_normalize = [col for col in norm_ratings.columns if col.endswith('Att')]

# Iterate over the selected columns and apply normalization
for column in columns_to_normalize:

    # Apply the NormalizeData function to scale the column
    norm_ratings[column] = NormalizeData(norm_ratings[column])

norm_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Shot Stopping Att,Aerial Att,Sweeping Att,Short Dist Att,Long Dist Att
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,GK,England League One 2025-26,24.0,800000,30/06/2028,no,4143,0.684690,0.756972,0.421080,0.580538,0.421147
870,G. Wickens,Lincoln City,Lincoln City,GK,GK,England League One 2025-26,24.0,150000,30/06/2028,no,4087,0.653112,0.679685,0.289840,0.352492,0.894417
871,S. Walker,Bradford City,Bradford City,GK,GK,England League One 2025-26,34.0,125000,30/06/2027,no,4086,0.530889,0.797209,0.291138,0.222120,0.426865
875,Joel Pereira,Reading,Reading,GK,GK,England League One 2025-26,29.0,250000,30/06/2028,no,4022,0.473331,0.806717,0.432418,0.793458,0.407766
884,J. Keeley,Luton Town,Luton Town,GK,GK,England League One 2025-26,22.0,200000,30/06/2027,no,3919,0.489598,0.719140,0.494682,0.716555,0.406966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,GK,England League Two 2025-26,29.0,100000,30/06/2026,no,1093,0.391382,0.842876,0.484613,0.545131,0.425565
19778,J. Wollacott,Crawley Town,Crawley Town,GK,GK,England League Two 2025-26,29.0,300000,30/06/2026,no,910,0.332559,0.826708,0.593437,0.778014,0.220275
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,GK,England League Two 2025-26,20.0,0,31/05/2026,no,596,0.184914,0.653560,0.369645,0.000880,0.608158
19866,S. Waller,Harrogate Town,Harrogate Town,GK,GK,England League Two 2025-26,22.0,0,30/06/2026,no,528,0.869554,0.871978,0.233964,0.620643,0.390823
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,GK,England League Two 2025-26,30.0,200000,30/06/2027,no,499,0.661417,0.878445,0.452260,0.592590,0.862691

### Weighting the Attributes to Create an Overall Rating

In [12]:
# Weight the overall attributes in terms of importance 
weighted_ratings = norm_ratings.copy()

#Weight the overall ratings
weighted_ratings['Shot Stopping Att'] =  weighted_ratings['Shot Stopping Att']    * 0.35
weighted_ratings['Aerial Att'] =         weighted_ratings['Aerial Att']           * 0.35
weighted_ratings['Sweeping Att'] =       weighted_ratings['Sweeping Att']         * 0.10
weighted_ratings['Short Dist Att'] =     weighted_ratings['Short Dist Att']       * 0.10
weighted_ratings['Long Dist Att'] =      weighted_ratings['Long Dist Att']        * 0.10


weighted_ratings['GK Rating'] = ( weighted_ratings['Shot Stopping Att'] 
                                + weighted_ratings['Aerial Att'] 
                                + weighted_ratings['Sweeping Att'] 
                                + weighted_ratings['Short Dist Att'] 
                                + weighted_ratings['Long Dist Att']
                                )

weighted_ratings

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,Minutes played,Shot Stopping Att,Aerial Att,Sweeping Att,Short Dist Att,Long Dist Att,GK Rating
869,S. Tickle,Wigan Athletic,Wigan Athletic,GK,GK,England League One 2025-26,24.0,800000,30/06/2028,no,4143,0.239641,0.264940,0.042108,0.058054,0.042115,0.646858
870,G. Wickens,Lincoln City,Lincoln City,GK,GK,England League One 2025-26,24.0,150000,30/06/2028,no,4087,0.228589,0.237890,0.028984,0.035249,0.089442,0.620154
871,S. Walker,Bradford City,Bradford City,GK,GK,England League One 2025-26,34.0,125000,30/06/2027,no,4086,0.185811,0.279023,0.029114,0.022212,0.042686,0.558847
875,Joel Pereira,Reading,Reading,GK,GK,England League One 2025-26,29.0,250000,30/06/2028,no,4022,0.165666,0.282351,0.043242,0.079346,0.040777,0.611381
884,J. Keeley,Luton Town,Luton Town,GK,GK,England League One 2025-26,22.0,200000,30/06/2027,no,3919,0.171359,0.251699,0.049468,0.071655,0.040697,0.584879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19740,N. Tzanev,Huddersfield Town,Newport County,GK,GK,England League Two 2025-26,29.0,100000,30/06/2026,no,1093,0.136984,0.295007,0.048461,0.054513,0.042556,0.577521
19778,J. Wollacott,Crawley Town,Crawley Town,GK,GK,England League Two 2025-26,29.0,300000,30/06/2026,no,910,0.116396,0.289348,0.059344,0.077801,0.022028,0.564916
19848,E. Harrison,Manchester United U21,Shrewsbury Town,GK,GK,England League Two 2025-26,20.0,0,31/05/2026,no,596,0.064720,0.228746,0.036964,0.000088,0.060816,0.391334
19866,S. Waller,Harrogate Town,Harrogate Town,GK,GK,England League Two 2025-26,22.0,0,30/06/2026,no,528,0.304344,0.305192,0.023396,0.062064,0.039082,0.734079
19877,L. McGee,Tranmere Rovers,Tranmere Rovers,GK,GK,England League Two 2025-26,30.0,200000,30/06/2027,no,499,0.231496,0.307456,0.045226,0.059259,0.086269,0.729706

In [13]:
# Final time to normalise, this time for the overall rating 

# Ensure a copy of the DataFrame to prevent unintended changes
final_ratings = weighted_ratings.copy()

# Select the attribute and rating columns in the DataFrame
columns_to_normalize = [col for col in final_ratings.columns if col.endswith('Att') or col.endswith('Rating')]

# Normalise the attribute and rating columns
for column in columns_to_normalize:
    final_ratings[column] = NormalizeData(final_ratings[column]) # function defined earlier

# Multiply columns ending with 'Att' or 'Rating' by 100 and round to 2 decimal places
final_ratings[columns_to_normalize] = (final_ratings[columns_to_normalize] * 100).round(2)

# Sort the DataFrame by the last column in descending order
rating_column = [col for col in final_ratings.columns if col.endswith('Rating')]
final_ratings.sort_values(by=rating_column, ascending=False, inplace=True)

# Merge the absolute values
final_ratings = final_ratings.merge(absolute_values,on=['Player','Team within selected timeframe'], how='left')

# Reset the index of the sorted DataFrame to ensure a clean, sequential index
final_ratings.reset_index(drop=True, inplace=True)

# Export the ratings to CSV
final_ratings.to_csv(rating_export_name, index=False)
print(f"Ratings exported at {datetime.now().strftime('%d-%m-%Y %H:%M')}")

final_ratings

Ratings exported at 18-05-2026 16:35

,Player,Team,Team within selected timeframe,Main Position,Position,League,Age,Market value,Contract expires,On loan,...,"Aerial duels won, %",Aerial duels per 90,Exits per 90,PAdj Interceptions,"Accurate short / medium passes, %",Short / medium passes per 90,"Average pass length, m","Accurate long passes, %",Long passes per 90,"Average long pass length, m"
0,A. Bass,Peterborough United,Peterborough United,GK,GK,England League One 2025-26,28.0,275000,30/06/2028,no,...,89.47,0.50,2.39,3.85,97.08,28.20,31.17,56.03,14.96,49.37
1,J. Chapman,Crawley Town,Crawley Town,GK,GK,England League Two 2025-26,25.0,100000,30/06/2027,yes,...,100.00,0.32,1.91,3.17,97.97,18.33,36.95,58.72,18.28,50.30
2,G. Smith,Bromley,Bromley,GK,GK,England League Two 2025-26,32.0,0,30/06/2026,no,...,90.48,0.47,1.26,1.75,95.50,2.49,50.14,66.67,12.74,54.39
3,M. Hudson,Oldham Athletic,Oldham Athletic,GK,GK,England League Two 2025-26,27.0,0,30/06/2028,no,...,84.00,0.53,1.63,2.87,98.43,6.82,45.32,68.06,14.33,54.90
4,J. Smith,Grimsby Town,Grimsby Town,GK,GK,England League Two 2025-26,24.0,200000,30/06/2028,yes,...,78.57,0.59,1.56,2.81,97.78,13.29,36.74,67.45,12.57,52.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,L. Southwood,Bristol Rovers,Bristol Rovers,GK,GK,England League Two 2025-26,28.0,500000,30/06/2027,no,...,50.00,0.16,1.01,2.55,98.63,11.75,40.48,66.06,15.59,52.70
72,T. Cann,Rotherham United,Rotherham United,GK,GK,England League One 2025-26,25.0,100000,30/06/2027,no,...,0.00,0.00,1.99,1.90,97.40,7.67,42.71,48.94,14.05,51.43
73,W. Jonathan Dennis,Leyton Orient,Leyton Orient,GK,GK,England League One 2025-26,25.0,350000,30/06/2028,yes,...,0.00,0.00,1.66,1.67,97.24,12.69,33.58,47.06,8.93,53.37
74,C. Pym,Grimsby Town,Grimsby Town,GK,GK,England League Two 2025-26,30.0,450000,30/06/2027,no,...,62.50,0.38,0.58,1.46,97.76,12.86,38.15,70.08,12.19,52.77
75,J. McDonnell,AFC Wimbledon,AFC Wimbledon,GK,GK,England League One 2025-26,31.0,0,30/06/2027,no,...,0.00,0.00,1.04,0.96,94.00,7.45,44.30,59.41,15.05,52.96